## INDIAN START UPS ECOSYSTEM ANALYSIS IN 2018-2021

## 1. BUSINESS UNDERSTANDING

Our Team, Santa Fe is trying to venture into the Indian Startup Ecosystem.  With numerous of successful enterprises earning the coveted "unicorn" label, India has become a favored investment destination. Our team will make an effort to respond by analyzing the data from 2018-2021 in order to focus our search for the best course of action for investment as a young organization.

## 2. DATA COLLECTION AND DATA PREPARATION
   ## 2.1 DATA COLLECTION

Provided with 4 datasets - the first 2 are to be imported from LP1 database, one exits in onedrive and the other is found in Github Repository.

In [2967]:
# DATA IMPORTS IN THE LP1 DATABASE
# 1. Install pyodbc and python-dotenv
%pip install pyodbc  
%pip install python-dotenv

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [2968]:
## Import all the necessary packages

import pyodbc                    #just installed with pip
from dotenv import dotenv_values #import the dotenv_values function from the dotenv package
import pandas as pd
import numpy as np
import warnings 
import matplotlib.pyplot as plt
import re

# Set the display format for floats
pd.options.display.float_format = '{:.2f}'.format

warnings.filterwarnings('ignore')

In [2969]:
# Load environment variables from .env file into a dictionary
environment_variables = dotenv_values('.env')


# Get the values for the credentials you set in the '.env' file
database = environment_variables.get("DATABASE")
server = environment_variables.get("SERVER")
username = environment_variables.get("USERNAME")
password = environment_variables.get("PASSWORD")


connection_string = f"DRIVER={{SQL Server}};SERVER={server};DATABASE={database};UID={username};PWD={password}"

In [2970]:
# Use the connect method of the pyodbc library and pass in the connection string.
# This will connect to the server and might take a few seconds to be complete. 
# Check your internet connection if it takes more time than necessary

connection = pyodbc.connect(connection_string)

In [2971]:
# Now the sql query to get the data is what what you see below. 
# Note that you will not have permissions to insert delete or update this database table. 

query = "Select * from dbo.LP1_startup_funding2020"
data20 = pd.read_sql(query, connection)
data20.head()

Company_Brand  Founded HeadQuarter              Sector   
0    Aqgromalin  2019.00     Chennai            AgriTech  \
1      Krayonnz  2019.00   Bangalore              EdTech   
2  PadCare Labs  2018.00        Pune  Hygiene management   
3         NCOME  2020.00   New Delhi              Escrow   
4    Gramophone  2016.00      Indore            AgriTech   

                                        What_it_does   
0                       Cultivating Ideas for Profit  \
1  An academy-guardian-scholar centric ecosystem ...   
2   Converting bio-hazardous waste to harmless waste   
3                       Escrow-as-a-service platform   
4  Gramophone is an AgTech platform enabling acce...   

                                            Founders   
0                    Prasanna Manogaran, Bharani C L  \
1                   Saurabh Dixit, Gurudutt Upadhyay   
2                                    Ajinkya Dhariya   
3                                      Ritesh Tiwari   
4  Ashish Rajan Singh, Harshit Gupta, Nishant Mah...   

                              Investor    Amount     Stage column10  
0                      Angel investors 200000.00      None     None  
1                      GSF Accelerator 100000.00  Pre-seed     None  
2                       Venture Center       NaN  Pre-seed     None  
3  Venture Catalysts, PointOne Capital 400000.00      None     None  
4  Siana Capital Management, Info Edge 340000.00      None     None

In [2972]:
data20.columns

Index(['Company_Brand', 'Founded', 'HeadQuarter', 'Sector', 'What_it_does',
       'Founders', 'Investor', 'Amount', 'Stage', 'column10'],
      dtype='object')

In [2973]:
# Importing the Table 2.
query = "Select * from dbo.LP1_startup_funding2021"
data21 = pd.read_sql(query, connection)
data21.head()

Company_Brand  Founded HeadQuarter          Sector   
0  Unbox Robotics  2019.00   Bangalore      AI startup  \
1          upGrad  2015.00      Mumbai          EdTech   
2     Lead School  2012.00      Mumbai          EdTech   
3         Bizongo  2015.00      Mumbai  B2B E-commerce   
4        FypMoney  2021.00    Gurugram         FinTech   

                                        What_it_does   
0  Unbox Robotics builds on-demand AI-driven ware...  \
1     UpGrad is an online higher education platform.   
2  LEAD School offers technology based school tra...   
3  Bizongo is a business-to-business online marke...   
4  FypMoney is Digital NEO Bank for Teenagers, em...   

                                            Founders   
0                        Pramod Ghadge, Shahid Memon  \
1  Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...   
2                         Smita Deorah, Sumeet Mehta   
3            Aniket Deb, Ankit Tomar, Sachin Agrawal   
4                                      Kapil Banwari   

                                        Investor        Amount         Stage  
0                    BEENEXT, Entrepreneur First    $1,200,000  Pre-series A  
1       Unilazer Ventures, IIFL Asset Management  $120,000,000          None  
2               GSV Ventures, Westbridge Capital   $30,000,000      Series D  
3                         CDC Group, IDG Capital   $51,000,000      Series C  
4  Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal    $2,000,000          Seed

In [2974]:
data21.columns

Index(['Company_Brand', 'Founded', 'HeadQuarter', 'Sector', 'What_it_does',
       'Founders', 'Investor', 'Amount', 'Stage'],
      dtype='object')

In [2975]:
# Second Data from one Drive
data19 = pd.read_csv('startup_funding2019.csv')

data19.head()

Company/Brand  Founded HeadQuarter           Sector   
0  Bombay Shaving      NaN         NaN        Ecommerce  \
1       Ruangguru  2014.00      Mumbai           Edtech   
2        Eduisfun      NaN      Mumbai           Edtech   
3        HomeLane  2014.00     Chennai  Interior design   
4        Nu Genes  2004.00   Telangana         AgriTech   

                                        What it does   
0         Provides a range of male grooming products  \
1  A learning platform that provides topic-based ...   
2            It aims to make learning fun via games.   
3              Provides interior designing solutions   
4  It is a seed company engaged in production, pr...   

                                Founders   
0                     Shantanu Deshpande  \
1  Adamas Belva Syah Devara, Iman Usman.   
2                          Jatin Solanki   
3           Srikanth Iyer, Rama Harinath   
4                 Narayana Reddy Punyala   

                                            Investor     Amount($)   
0                               Sixth Sense Ventures    $6,300,000  \
1                                   General Atlantic  $150,000,000   
2     Deepak Parekh, Amitabh Bachchan, Piyush Pandey   $28,000,000   
3  Evolvence India Fund (EIF), Pidilite Group, FJ...   $30,000,000   
4           Innovation in Food and Agriculture (IFA)    $6,000,000   

           Stage  
0            NaN  
1       Series C  
2  Fresh funding  
3       Series D  
4            NaN

In [2976]:
data19.columns

Index(['Company/Brand', 'Founded', 'HeadQuarter', 'Sector', 'What it does',
       'Founders', 'Investor', 'Amount($)', 'Stage'],
      dtype='object')

In [2977]:
# 3rd Data Set from git hub respository
data18 = pd.read_csv('startup_funding2018.csv')

data18.head()

Company Name                                           Industry   
0  TheCollegeFever  Brand Marketing, Event Promotion, Marketing, S...  \
1  Happy Cow Dairy                               Agriculture, Farming   
2       MyLoanCare   Credit, Financial Services, Lending, Marketplace   
3      PayMe India                        Financial Services, FinTech   
4         Eunimart                 E-Commerce Platforms, Retail, SaaS   

  Round/Series       Amount                          Location   
0         Seed       250000       Bangalore, Karnataka, India  \
1         Seed  ₹40,000,000        Mumbai, Maharashtra, India   
2     Series A  ₹65,000,000           Gurgaon, Haryana, India   
3        Angel      2000000       Noida, Uttar Pradesh, India   
4         Seed            —  Hyderabad, Andhra Pradesh, India   

                                       About Company  
0  TheCollegeFever is a hub for fun, fiesta and f...  
1  A startup which aggregates milk from dairy far...  
2          Leading Online Loans Marketplace in India  
3  PayMe India is an innovative FinTech organizat...  
4  Eunimart is a one stop solution for merchants ...

In [2978]:
data18.columns

Index(['Company Name', 'Industry', 'Round/Series', 'Amount', 'Location',
       'About Company'],
      dtype='object')

## HYPOTHESIS FORMULATION


Null Hypotheis - The tech sector doesnt have highest Sucess rate of being funded.

Alternative Hypothesis - The tech Sector has highest success rate of being funded  and investors should venture in the Tech Industry in Indian.


QUESTIONS

The following questions were asked to assist in the data analysis process:

1. Which company has the highest funding?
2. Which sector has the highest funding?
3. Who are the top 10 investors and the sectors have they invested in?
4. What is total amount of funding received in each year?
5. The top funded sector in the years 2018, 2019, 2020 and 2021.
6. Which is location recieved most funding?
7. At what stage do start up recieve most funding?

   ## 2.2 DATA CLEANING

### 2.2.1. Cleaning the 2018 dataset

In [2979]:
# Cleaning the 2019 dataset
data18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 526 entries, 0 to 525
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Company Name   526 non-null    object
 1   Industry       526 non-null    object
 2   Round/Series   526 non-null    object
 3   Amount         526 non-null    object
 4   Location       526 non-null    object
 5   About Company  526 non-null    object
dtypes: object(6)
memory usage: 24.8+ KB


### I. Dropping the columns not needed for analysis

In [2980]:
# Dropping the 'About' columns since it is not present in the other datasets
data18 = data18.drop('About Company', axis=1)
data18.head()

Company Name                                           Industry   
0  TheCollegeFever  Brand Marketing, Event Promotion, Marketing, S...  \
1  Happy Cow Dairy                               Agriculture, Farming   
2       MyLoanCare   Credit, Financial Services, Lending, Marketplace   
3      PayMe India                        Financial Services, FinTech   
4         Eunimart                 E-Commerce Platforms, Retail, SaaS   

  Round/Series       Amount                          Location  
0         Seed       250000       Bangalore, Karnataka, India  
1         Seed  ₹40,000,000        Mumbai, Maharashtra, India  
2     Series A  ₹65,000,000           Gurgaon, Haryana, India  
3        Angel      2000000       Noida, Uttar Pradesh, India  
4         Seed            —  Hyderabad, Andhra Pradesh, India

### II. Check for duplicates in the dataset


In [2981]:
# Check for duplicates
duplicates = data18.duplicated(keep=False)

# Returns the total number of duplicates
duplicates_count = duplicates.value_counts()
duplicates_count


False    524
True       2
Name: count, dtype: int64

In [2982]:
# Identifying the duplicate rows
duplicates = data18[data18.duplicated(keep=False)]
duplicates

Company Name                                           Industry   
0    TheCollegeFever  Brand Marketing, Event Promotion, Marketing, S...  \
348  TheCollegeFever  Brand Marketing, Event Promotion, Marketing, S...   

    Round/Series  Amount                     Location  
0           Seed  250000  Bangalore, Karnataka, India  
348         Seed  250000  Bangalore, Karnataka, India

##### We can see there is only one duplicated row, let's drop the row

In [2983]:
# Dropping one of the duplicated row
data18.drop_duplicates(keep='first', inplace=True)


In [2984]:
# Confirm if the duplicate rows have been dropped
duplicates = data18[data18.duplicated(keep=False)]
duplicates

Empty DataFrame
Columns: [Company Name, Industry, Round/Series, Amount, Location]
Index: []

### III. Check for missing values

In [2985]:
missing_values_data18 = data18.isnull().sum()
missing_values_data18

Company Name    0
Industry        0
Round/Series    0
Amount          0
Location        0
dtype: int64

#### We can see that there are no missing values. But missing values can be represented using '-', let's check 

In [2986]:
# Replacing '-' with NaN
data18.replace("—", np.nan, inplace=True)

# Check for missing values
missing_values_data18 = data18.isnull().sum()
missing_values_data18

Company Name      0
Industry         30
Round/Series      0
Amount          148
Location          0
dtype: int64

#### Now we can see that we have a lot of missing values. Let's try dealing with the missing values

In [2987]:
# Cleaning the 'Industry' column by replacing the missing values with 'Unknown'
data18['Industry'] = data18['Industry'].fillna('Unknown')
data18.head(10)

Company Name                                           Industry   
0     TheCollegeFever  Brand Marketing, Event Promotion, Marketing, S...  \
1     Happy Cow Dairy                               Agriculture, Farming   
2          MyLoanCare   Credit, Financial Services, Lending, Marketplace   
3         PayMe India                        Financial Services, FinTech   
4            Eunimart                 E-Commerce Platforms, Retail, SaaS   
5              Hasura                   Cloud Infrastructure, PaaS, SaaS   
6           Tripshelf                     Internet, Leisure, Marketplace   
7        Hyperdata.IO                                    Market Research   
8        Freightwalla       Information Services, Information Technology   
9  Microchip Payments                                    Mobile Payments   

  Round/Series       Amount                          Location  
0         Seed       250000       Bangalore, Karnataka, India  
1         Seed  ₹40,000,000        Mumbai, Maharashtra, India  
2     Series A  ₹65,000,000           Gurgaon, Haryana, India  
3        Angel      2000000       Noida, Uttar Pradesh, India  
4         Seed          NaN  Hyderabad, Andhra Pradesh, India  
5         Seed      1600000       Bengaluru, Karnataka, India  
6         Seed  ₹16,000,000             Kalkaji, Delhi, India  
7        Angel  ₹50,000,000  Hyderabad, Andhra Pradesh, India  
8         Seed          NaN        Mumbai, Maharashtra, India  
9         Seed          NaN       Bangalore, Karnataka, India

In [2988]:
# Cleaning the Location column by splitting at the commas
data18['Industry'].unique()

array(['Brand Marketing, Event Promotion, Marketing, Sponsorship, Ticketing',
       'Agriculture, Farming',
       'Credit, Financial Services, Lending, Marketplace',
       'Financial Services, FinTech',
       'E-Commerce Platforms, Retail, SaaS',
       'Cloud Infrastructure, PaaS, SaaS',
       'Internet, Leisure, Marketplace', 'Market Research',
       'Information Services, Information Technology', 'Mobile Payments',
       'B2B, Shoes', 'Internet',
       'Apps, Collaboration, Developer Platform, Enterprise Software, Messaging, Productivity Tools, Video Chat',
       'Food Delivery', 'Industrial Automation',
       'Automotive, Search Engine, Service Industry',
       'Finance, Internet, Travel',
       'Accounting, Business Information Systems, Business Travel, Finance, SaaS',
       'Artificial Intelligence, Product Search, SaaS, Service Industry, Software',
       'Internet of Things, Waste Management',
       'Air Transportation, Freight Service, Logistics, Marine Transport

In [2989]:
# Cleaning the Location Industry by splitting at the commas
data18[["City", "State", "Country"]]= data18['Location'].str.split(',', expand=True)
data18

Company Name                                           Industry   
0      TheCollegeFever  Brand Marketing, Event Promotion, Marketing, S...  \
1      Happy Cow Dairy                               Agriculture, Farming   
2           MyLoanCare   Credit, Financial Services, Lending, Marketplace   
3          PayMe India                        Financial Services, FinTech   
4             Eunimart                 E-Commerce Platforms, Retail, SaaS   
..                 ...                                                ...   
521              Udaan   B2B, Business Development, Internet, Marketplace   
522  Happyeasygo Group                                    Tourism, Travel   
523             Mombay         Food and Beverage, Food Delivery, Internet   
524         Droni Tech                             Information Technology   
525            Netmeds         Biotechnology, Health Care, Pharmaceutical   

    Round/Series       Amount                          Location       City   
0           Seed       250000       Bangalore, Karnataka, India  Bangalore  \
1           Seed  ₹40,000,000        Mumbai, Maharashtra, India     Mumbai   
2       Series A  ₹65,000,000           Gurgaon, Haryana, India    Gurgaon   
3          Angel      2000000       Noida, Uttar Pradesh, India      Noida   
4           Seed          NaN  Hyderabad, Andhra Pradesh, India  Hyderabad   
..           ...          ...                               ...        ...   
521     Series C    225000000       Bangalore, Karnataka, India  Bangalore   
522     Series A          NaN           Haryana, Haryana, India    Haryana   
523         Seed         7500        Mumbai, Maharashtra, India     Mumbai   
524         Seed  ₹35,000,000        Mumbai, Maharashtra, India     Mumbai   
525     Series C     35000000        Chennai, Tamil Nadu, India    Chennai   

               State Country  
0          Karnataka   India  
1        Maharashtra   India  
2            Haryana   India  
3      Uttar Pradesh   India  
4     Andhra Pradesh   India  
..               ...     ...  
521        Karnataka   India  
522          Haryana   India  
523      Maharashtra   India  
524      Maharashtra   India  
525       Tamil Nadu   India  

[525 rows x 8 columns]

In [2990]:
# Replace '$' currency symbol and commas with empty string
data18['Amount'] = data18['Amount'].str.replace(',', '', regex=False).str.replace('$', '', regex=False)

# Cleaning the 'Amount' column by converting Indian Rupees to USD
data18.loc[data18['Amount'].astype(str).str.contains('₹'), 'Amount'] = data18.loc[data18['Amount'].astype(str).str.contains('₹'),'Amount'].apply(lambda x: float(x.replace('₹', ''))*0.012)

# Converting the 'Amount' column to numeric datatype, replacing any non-numeric values with NaN
data18['Amount'] = pd.to_numeric(data18['Amount'], errors='coerce')

# Rename column "Amount" to "Amount($)"
data18.rename(columns={'Amount':'Amount($)'}, inplace=True)

# Convert Amount($) column from object to float datatype
data18['Amount($)'] = data18['Amount($)'].astype(float)

data18

Company Name                                           Industry   
0      TheCollegeFever  Brand Marketing, Event Promotion, Marketing, S...  \
1      Happy Cow Dairy                               Agriculture, Farming   
2           MyLoanCare   Credit, Financial Services, Lending, Marketplace   
3          PayMe India                        Financial Services, FinTech   
4             Eunimart                 E-Commerce Platforms, Retail, SaaS   
..                 ...                                                ...   
521              Udaan   B2B, Business Development, Internet, Marketplace   
522  Happyeasygo Group                                    Tourism, Travel   
523             Mombay         Food and Beverage, Food Delivery, Internet   
524         Droni Tech                             Information Technology   
525            Netmeds         Biotechnology, Health Care, Pharmaceutical   

    Round/Series    Amount($)                          Location       City   
0           Seed    250000.00       Bangalore, Karnataka, India  Bangalore  \
1           Seed    480000.00        Mumbai, Maharashtra, India     Mumbai   
2       Series A    780000.00           Gurgaon, Haryana, India    Gurgaon   
3          Angel   2000000.00       Noida, Uttar Pradesh, India      Noida   
4           Seed          NaN  Hyderabad, Andhra Pradesh, India  Hyderabad   
..           ...          ...                               ...        ...   
521     Series C 225000000.00       Bangalore, Karnataka, India  Bangalore   
522     Series A          NaN           Haryana, Haryana, India    Haryana   
523         Seed      7500.00        Mumbai, Maharashtra, India     Mumbai   
524         Seed    420000.00        Mumbai, Maharashtra, India     Mumbai   
525     Series C  35000000.00        Chennai, Tamil Nadu, India    Chennai   

               State Country  
0          Karnataka   India  
1        Maharashtra   India  
2            Haryana   India  
3      Uttar Pradesh   India  
4     Andhra Pradesh   India  
..               ...     ...  
521        Karnataka   India  
522          Haryana   India  
523      Maharashtra   India  
524      Maharashtra   India  
525       Tamil Nadu   India  

[525 rows x 8 columns]

In [2991]:
# Replace NaN values in 'Amount($)' column with median
# Calculate the median of 'Amount($)' column
mean_amount = data18['Amount($)'].mean()

# Replacing NaN with the mean
data18['Amount($)'].fillna(value=mean_amount, inplace=True)

data18

Company Name                                           Industry   
0      TheCollegeFever  Brand Marketing, Event Promotion, Marketing, S...  \
1      Happy Cow Dairy                               Agriculture, Farming   
2           MyLoanCare   Credit, Financial Services, Lending, Marketplace   
3          PayMe India                        Financial Services, FinTech   
4             Eunimart                 E-Commerce Platforms, Retail, SaaS   
..                 ...                                                ...   
521              Udaan   B2B, Business Development, Internet, Marketplace   
522  Happyeasygo Group                                    Tourism, Travel   
523             Mombay         Food and Beverage, Food Delivery, Internet   
524         Droni Tech                             Information Technology   
525            Netmeds         Biotechnology, Health Care, Pharmaceutical   

    Round/Series    Amount($)                          Location       City   
0           Seed    250000.00       Bangalore, Karnataka, India  Bangalore  \
1           Seed    480000.00        Mumbai, Maharashtra, India     Mumbai   
2       Series A    780000.00           Gurgaon, Haryana, India    Gurgaon   
3          Angel   2000000.00       Noida, Uttar Pradesh, India      Noida   
4           Seed  17030531.59  Hyderabad, Andhra Pradesh, India  Hyderabad   
..           ...          ...                               ...        ...   
521     Series C 225000000.00       Bangalore, Karnataka, India  Bangalore   
522     Series A  17030531.59           Haryana, Haryana, India    Haryana   
523         Seed      7500.00        Mumbai, Maharashtra, India     Mumbai   
524         Seed    420000.00        Mumbai, Maharashtra, India     Mumbai   
525     Series C  35000000.00        Chennai, Tamil Nadu, India    Chennai   

               State Country  
0          Karnataka   India  
1        Maharashtra   India  
2            Haryana   India  
3      Uttar Pradesh   India  
4     Andhra Pradesh   India  
..               ...     ...  
521        Karnataka   India  
522          Haryana   India  
523      Maharashtra   India  
524      Maharashtra   India  
525       Tamil Nadu   India  

[525 rows x 8 columns]

In [2992]:
# Creating a year column and filling with 2018
data18.insert(0,'Year', 2018)
data18.head()

Year     Company Name                                           Industry   
0  2018  TheCollegeFever  Brand Marketing, Event Promotion, Marketing, S...  \
1  2018  Happy Cow Dairy                               Agriculture, Farming   
2  2018       MyLoanCare   Credit, Financial Services, Lending, Marketplace   
3  2018      PayMe India                        Financial Services, FinTech   
4  2018         Eunimart                 E-Commerce Platforms, Retail, SaaS   

  Round/Series   Amount($)                          Location       City   
0         Seed   250000.00       Bangalore, Karnataka, India  Bangalore  \
1         Seed   480000.00        Mumbai, Maharashtra, India     Mumbai   
2     Series A   780000.00           Gurgaon, Haryana, India    Gurgaon   
3        Angel  2000000.00       Noida, Uttar Pradesh, India      Noida   
4         Seed 17030531.59  Hyderabad, Andhra Pradesh, India  Hyderabad   

             State Country  
0        Karnataka   India  
1      Maharashtra   India  
2          Haryana   India  
3    Uttar Pradesh   India  
4   Andhra Pradesh   India

In [2993]:
# Cleaning the Location column by splitting at the commas
data18[["City", "State", "Country"]]= data18['Location'].str.split(',', expand=True)
data18

Year       Company Name   
0    2018    TheCollegeFever  \
1    2018    Happy Cow Dairy   
2    2018         MyLoanCare   
3    2018        PayMe India   
4    2018           Eunimart   
..    ...                ...   
521  2018              Udaan   
522  2018  Happyeasygo Group   
523  2018             Mombay   
524  2018         Droni Tech   
525  2018            Netmeds   

                                              Industry Round/Series   
0    Brand Marketing, Event Promotion, Marketing, S...         Seed  \
1                                 Agriculture, Farming         Seed   
2     Credit, Financial Services, Lending, Marketplace     Series A   
3                          Financial Services, FinTech        Angel   
4                   E-Commerce Platforms, Retail, SaaS         Seed   
..                                                 ...          ...   
521   B2B, Business Development, Internet, Marketplace     Series C   
522                                    Tourism, Travel     Series A   
523         Food and Beverage, Food Delivery, Internet         Seed   
524                             Information Technology         Seed   
525         Biotechnology, Health Care, Pharmaceutical     Series C   

       Amount($)                          Location       City   
0      250000.00       Bangalore, Karnataka, India  Bangalore  \
1      480000.00        Mumbai, Maharashtra, India     Mumbai   
2      780000.00           Gurgaon, Haryana, India    Gurgaon   
3     2000000.00       Noida, Uttar Pradesh, India      Noida   
4    17030531.59  Hyderabad, Andhra Pradesh, India  Hyderabad   
..           ...                               ...        ...   
521 225000000.00       Bangalore, Karnataka, India  Bangalore   
522  17030531.59           Haryana, Haryana, India    Haryana   
523      7500.00        Mumbai, Maharashtra, India     Mumbai   
524    420000.00        Mumbai, Maharashtra, India     Mumbai   
525  35000000.00        Chennai, Tamil Nadu, India    Chennai   

               State Country  
0          Karnataka   India  
1        Maharashtra   India  
2            Haryana   India  
3      Uttar Pradesh   India  
4     Andhra Pradesh   India  
..               ...     ...  
521        Karnataka   India  
522          Haryana   India  
523      Maharashtra   India  
524      Maharashtra   India  
525       Tamil Nadu   India  

[525 rows x 9 columns]

In [2994]:
# Dropping the Country and Location column as it is not needed for the analysis
columns_to_drop = ['Country','Location','State']
data18.drop(columns_to_drop, axis=1, inplace=True)
data18.head()

Year     Company Name                                           Industry   
0  2018  TheCollegeFever  Brand Marketing, Event Promotion, Marketing, S...  \
1  2018  Happy Cow Dairy                               Agriculture, Farming   
2  2018       MyLoanCare   Credit, Financial Services, Lending, Marketplace   
3  2018      PayMe India                        Financial Services, FinTech   
4  2018         Eunimart                 E-Commerce Platforms, Retail, SaaS   

  Round/Series   Amount($)       City  
0         Seed   250000.00  Bangalore  
1         Seed   480000.00     Mumbai  
2     Series A   780000.00    Gurgaon  
3        Angel  2000000.00      Noida  
4         Seed 17030531.59  Hyderabad

In [2995]:
# Check for missing values
data18.isna().sum()

Year            0
Company Name    0
Industry        0
Round/Series    0
Amount($)       0
City            0
dtype: int64

In [2996]:
# Check the data types
data18.dtypes

Year              int64
Company Name     object
Industry         object
Round/Series     object
Amount($)       float64
City             object
dtype: object

In [2997]:
#Inspecting the City and State columns
data18['City'].unique()

array(['Bangalore', 'Mumbai', 'Gurgaon', 'Noida', 'Hyderabad',
       'Bengaluru', 'Kalkaji', 'Delhi', 'India', 'Hubli', 'New Delhi',
       'Chennai', 'Mohali', 'Kolkata', 'Pune', 'Jodhpur', 'Kanpur',
       'Ahmedabad', 'Azadpur', 'Haryana', 'Cochin', 'Faridabad', 'Jaipur',
       'Kota', 'Anand', 'Bangalore City', 'Belgaum', 'Thane', 'Margão',
       'Indore', 'Alwar', 'Kannur', 'Trivandrum', 'Ernakulam',
       'Kormangala', 'Uttar Pradesh', 'Andheri', 'Mylapore', 'Ghaziabad',
       'Kochi', 'Powai', 'Guntur', 'Kalpakkam', 'Bhopal', 'Coimbatore',
       'Worli', 'Alleppey', 'Chandigarh', 'Guindy', 'Lucknow'],
      dtype=object)

In [2998]:
# Replacing Bengaluru and Bangalore City with Bangalore
data18['City'] = data18['City'].str.replace('Bangalore','Bengaluru', case=False)
data18['City'] = data18['City'].str.replace('Bangalore City','Bengaluru', case=False) 
data18['City'].unique()

array(['Bengaluru', 'Mumbai', 'Gurgaon', 'Noida', 'Hyderabad', 'Kalkaji',
       'Delhi', 'India', 'Hubli', 'New Delhi', 'Chennai', 'Mohali',
       'Kolkata', 'Pune', 'Jodhpur', 'Kanpur', 'Ahmedabad', 'Azadpur',
       'Haryana', 'Cochin', 'Faridabad', 'Jaipur', 'Kota', 'Anand',
       'Bengaluru City', 'Belgaum', 'Thane', 'Margão', 'Indore', 'Alwar',
       'Kannur', 'Trivandrum', 'Ernakulam', 'Kormangala', 'Uttar Pradesh',
       'Andheri', 'Mylapore', 'Ghaziabad', 'Kochi', 'Powai', 'Guntur',
       'Kalpakkam', 'Bhopal', 'Coimbatore', 'Worli', 'Alleppey',
       'Chandigarh', 'Guindy', 'Lucknow'], dtype=object)

In [2999]:
#Renaming the City column to Headquarter and company name to company/Brand, same as round/series to stage
data18.rename(columns={'City':'HeadQuarter'}, inplace=True)
data18.rename(columns={'Company Name':'Company/Brand'}, inplace=True)
data18.rename(columns={'Round/Series':'Stage'}, inplace=True)
data18.rename(columns={'Industry':'Sector'}, inplace=True)

In [3000]:
data18

Year      Company/Brand   
0    2018    TheCollegeFever  \
1    2018    Happy Cow Dairy   
2    2018         MyLoanCare   
3    2018        PayMe India   
4    2018           Eunimart   
..    ...                ...   
521  2018              Udaan   
522  2018  Happyeasygo Group   
523  2018             Mombay   
524  2018         Droni Tech   
525  2018            Netmeds   

                                                Sector     Stage    Amount($)   
0    Brand Marketing, Event Promotion, Marketing, S...      Seed    250000.00  \
1                                 Agriculture, Farming      Seed    480000.00   
2     Credit, Financial Services, Lending, Marketplace  Series A    780000.00   
3                          Financial Services, FinTech     Angel   2000000.00   
4                   E-Commerce Platforms, Retail, SaaS      Seed  17030531.59   
..                                                 ...       ...          ...   
521   B2B, Business Development, Internet, Marketplace  Series C 225000000.00   
522                                    Tourism, Travel  Series A  17030531.59   
523         Food and Beverage, Food Delivery, Internet      Seed      7500.00   
524                             Information Technology      Seed    420000.00   
525         Biotechnology, Health Care, Pharmaceutical  Series C  35000000.00   

    HeadQuarter  
0     Bengaluru  
1        Mumbai  
2       Gurgaon  
3         Noida  
4     Hyderabad  
..          ...  
521   Bengaluru  
522     Haryana  
523      Mumbai  
524      Mumbai  
525     Chennai  

[525 rows x 6 columns]

In [3001]:
#Inspecting the Stage Column
data18['Stage'].unique()

array(['Seed', 'Series A', 'Angel', 'Series B', 'Pre-Seed',
       'Private Equity', 'Venture - Series Unknown', 'Grant',
       'Debt Financing', 'Post-IPO Debt', 'Series H', 'Series C',
       'Series E', 'Corporate Round', 'Undisclosed',
       'https://docs.google.com/spreadsheets/d/1x9ziNeaz6auNChIHnMI8U6kS7knTr3byy_YBGfQaoUA/edit#gid=1861303593',
       'Series D', 'Secondary Market', 'Post-IPO Equity',
       'Non-equity Assistance', 'Funding Round'], dtype=object)

In [3002]:
#Replace the 
data18['Stage'] = data18['Stage'].str.replace('https://docs.google.com/spreadsheets/d/1x9ziNeaz6auNChIHnMI8U6kS7knTr3byy_YBGfQaoUA/edit#gid=1861303593','Unavailable', case=False) 
data18['Stage'] = data18['Stage'].str.replace('Undisclosed','Unknown', case =False)

In [3003]:
data18['Stage'].unique()

array(['Seed', 'Series A', 'Angel', 'Series B', 'Pre-Seed',
       'Private Equity', 'Venture - Series Unknown', 'Grant',
       'Debt Financing', 'Post-IPO Debt', 'Series H', 'Series C',
       'Series E', 'Corporate Round', 'Unknown', 'Unavailable',
       'Series D', 'Secondary Market', 'Post-IPO Equity',
       'Non-equity Assistance', 'Funding Round'], dtype=object)

In [3004]:
data18['Sector'].unique()

array(['Brand Marketing, Event Promotion, Marketing, Sponsorship, Ticketing',
       'Agriculture, Farming',
       'Credit, Financial Services, Lending, Marketplace',
       'Financial Services, FinTech',
       'E-Commerce Platforms, Retail, SaaS',
       'Cloud Infrastructure, PaaS, SaaS',
       'Internet, Leisure, Marketplace', 'Market Research',
       'Information Services, Information Technology', 'Mobile Payments',
       'B2B, Shoes', 'Internet',
       'Apps, Collaboration, Developer Platform, Enterprise Software, Messaging, Productivity Tools, Video Chat',
       'Food Delivery', 'Industrial Automation',
       'Automotive, Search Engine, Service Industry',
       'Finance, Internet, Travel',
       'Accounting, Business Information Systems, Business Travel, Finance, SaaS',
       'Artificial Intelligence, Product Search, SaaS, Service Industry, Software',
       'Internet of Things, Waste Management',
       'Air Transportation, Freight Service, Logistics, Marine Transport

The final 2018 Cleaned Data Set

In [3005]:
data18.head()

Year    Company/Brand                                             Sector   
0  2018  TheCollegeFever  Brand Marketing, Event Promotion, Marketing, S...  \
1  2018  Happy Cow Dairy                               Agriculture, Farming   
2  2018       MyLoanCare   Credit, Financial Services, Lending, Marketplace   
3  2018      PayMe India                        Financial Services, FinTech   
4  2018         Eunimart                 E-Commerce Platforms, Retail, SaaS   

      Stage   Amount($) HeadQuarter  
0      Seed   250000.00   Bengaluru  
1      Seed   480000.00      Mumbai  
2  Series A   780000.00     Gurgaon  
3     Angel  2000000.00       Noida  
4      Seed 17030531.59   Hyderabad

  ### 2.2.2 Cleaning the 2019 dataset

In [3006]:
data19.head(10)

Company/Brand  Founded HeadQuarter           Sector   
0  Bombay Shaving      NaN         NaN        Ecommerce  \
1       Ruangguru  2014.00      Mumbai           Edtech   
2        Eduisfun      NaN      Mumbai           Edtech   
3        HomeLane  2014.00     Chennai  Interior design   
4        Nu Genes  2004.00   Telangana         AgriTech   
5        FlytBase      NaN        Pune       Technology   
6           Finly      NaN   Bangalore             SaaS   
7        Kratikal  2013.00       Noida       Technology   
8       Quantiphi      NaN         NaN        AI & Tech   
9        Lenskart  2010.00       Delhi       E-commerce   

                                        What it does   
0         Provides a range of male grooming products  \
1  A learning platform that provides topic-based ...   
2            It aims to make learning fun via games.   
3              Provides interior designing solutions   
4  It is a seed company engaged in production, pr...   
5                        A drone automation platform   
6  It builds software products that makes work si...   
7  It is a product-based cybersecurity solutions ...   
8  It is an AI and big data services company prov...   
9                            It is a eyewear company   

                                          Founders   
0                               Shantanu Deshpande  \
1            Adamas Belva Syah Devara, Iman Usman.   
2                                    Jatin Solanki   
3                     Srikanth Iyer, Rama Harinath   
4                           Narayana Reddy Punyala   
5                                      Nitin Gupta   
6                        Vivek AG, Veekshith C Rai   
7  Pavan Kushwaha, Paratosh Bansal, Dip Jung Thapa   
8                                   Renuka Ramnath   
9     Peyush Bansal, Amit Chaudhary, Sumeet Kapahi   

                                            Investor     Amount($)   
0                               Sixth Sense Ventures    $6,300,000  \
1                                   General Atlantic  $150,000,000   
2     Deepak Parekh, Amitabh Bachchan, Piyush Pandey   $28,000,000   
3  Evolvence India Fund (EIF), Pidilite Group, FJ...   $30,000,000   
4           Innovation in Food and Agriculture (IFA)    $6,000,000   
5                                        Undisclosed   Undisclosed   
6  Social Capital, AngelList India, Gemba Capital...   Undisclosed   
7         Gilda VC, Art Venture, Rajeev Chitrabhanu.    $1,000,000   
8               Multiples Alternate Asset Management   $20,000,000   
9                                           SoftBank  $275,000,000   

           Stage  
0            NaN  
1       Series C  
2  Fresh funding  
3       Series D  
4            NaN  
5            NaN  
6            NaN  
7   Pre series A  
8       Series A  
9       Series G

In [3007]:
data19.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Company/Brand  89 non-null     object 
 1   Founded        60 non-null     float64
 2   HeadQuarter    70 non-null     object 
 3   Sector         84 non-null     object 
 4   What it does   89 non-null     object 
 5   Founders       86 non-null     object 
 6   Investor       89 non-null     object 
 7   Amount($)      89 non-null     object 
 8   Stage          43 non-null     object 
dtypes: float64(1), object(8)
memory usage: 6.4+ KB


#### I. Dropping columns not needed for analysis

In [3008]:
# Dropping the columns not needed for analysis
columns_to_drop = ['What it does', 'Founded', 'Founders', 'Investor']  #Founded?
data19.drop(columns_to_drop, axis = 1, inplace=True)
data19


Company/Brand HeadQuarter                   Sector     Amount($)   
0    Bombay Shaving         NaN                Ecommerce    $6,300,000  \
1         Ruangguru      Mumbai                   Edtech  $150,000,000   
2          Eduisfun      Mumbai                   Edtech   $28,000,000   
3          HomeLane     Chennai          Interior design   $30,000,000   
4          Nu Genes   Telangana                 AgriTech    $6,000,000   
..              ...         ...                      ...           ...   
84     Infra.Market      Mumbai                Infratech   $20,000,000   
85              Oyo    Gurugram              Hospitality  $693,000,000   
86       GoMechanic       Delhi  Automobile & Technology    $5,000,000   
87           Spinny       Delhi               Automobile   $50,000,000   
88  Ess Kay Fincorp   Rajasthan                  Banking   $33,000,000   

            Stage  
0             NaN  
1        Series C  
2   Fresh funding  
3        Series D  
4             NaN  
..            ...  
84       Series A  
85            NaN  
86       Series B  
87            NaN  
88            NaN  

[89 rows x 5 columns]

#### II. Checking for duplicates

In [3009]:
# Check for duplicates
duplicates = data19.duplicated(keep=False)

# Returns the total number of duplicates
duplicates_count = duplicates.value_counts()
duplicates_count

False    89
Name: count, dtype: int64

#### III. Checking for missing values

In [3010]:
# Check for the missing
data19.isnull().sum()

Company/Brand     0
HeadQuarter      19
Sector            5
Amount($)         0
Stage            46
dtype: int64

##### The aren't many missing values so let's try inspecting them

In [3011]:
# Cleaning the Headquater column
data19['HeadQuarter'].unique()

array([nan, 'Mumbai', 'Chennai', 'Telangana', 'Pune', 'Bangalore',
       'Noida', 'Delhi', 'Ahmedabad', 'Gurugram', 'Haryana', 'Chandigarh',
       'Jaipur', 'New Delhi', 'Surat', 'Uttar pradesh', 'Hyderabad',
       'Rajasthan'], dtype=object)

In [3012]:
# Replacing the 'nan' with 'Unknown'
data19['HeadQuarter'] = data19['HeadQuarter'].fillna('Unknown')
data19['HeadQuarter'].unique()

array(['Unknown', 'Mumbai', 'Chennai', 'Telangana', 'Pune', 'Bangalore',
       'Noida', 'Delhi', 'Ahmedabad', 'Gurugram', 'Haryana', 'Chandigarh',
       'Jaipur', 'New Delhi', 'Surat', 'Uttar pradesh', 'Hyderabad',
       'Rajasthan'], dtype=object)

In [3013]:
# Cleaning the Sector column
data19['Sector'].unique()

array(['Ecommerce', 'Edtech', 'Interior design', 'AgriTech', 'Technology',
       'SaaS', 'AI & Tech', 'E-commerce', 'E-commerce & AR', 'Fintech',
       'HR tech', 'Food tech', 'Health', 'Healthcare', 'Safety tech',
       'Pharmaceutical', 'Insurance technology', 'AI', 'Foodtech', 'Food',
       'IoT', 'E-marketplace', 'Robotics & AI', 'Logistics', 'Travel',
       'Manufacturing', 'Food & Nutrition', 'Social Media', nan,
       'E-Sports', 'Cosmetics', 'B2B', 'Jewellery', 'B2B Supply Chain',
       'Games', 'Food & tech', 'Accomodation', 'Automotive tech',
       'Legal tech', 'Mutual Funds', 'Cybersecurity', 'Automobile',
       'Sports', 'Healthtech', 'Yoga & wellness', 'Virtual Banking',
       'Transportation', 'Transport & Rentals',
       'Marketing & Customer loyalty', 'Infratech', 'Hospitality',
       'Automobile & Technology', 'Banking'], dtype=object)

In [3014]:
# Replacing nan in Sector column with Unknown
data19['Sector'] = data19['Sector'].fillna('Unknown')
data19

Company/Brand HeadQuarter                   Sector     Amount($)   
0    Bombay Shaving     Unknown                Ecommerce    $6,300,000  \
1         Ruangguru      Mumbai                   Edtech  $150,000,000   
2          Eduisfun      Mumbai                   Edtech   $28,000,000   
3          HomeLane     Chennai          Interior design   $30,000,000   
4          Nu Genes   Telangana                 AgriTech    $6,000,000   
..              ...         ...                      ...           ...   
84     Infra.Market      Mumbai                Infratech   $20,000,000   
85              Oyo    Gurugram              Hospitality  $693,000,000   
86       GoMechanic       Delhi  Automobile & Technology    $5,000,000   
87           Spinny       Delhi               Automobile   $50,000,000   
88  Ess Kay Fincorp   Rajasthan                  Banking   $33,000,000   

            Stage  
0             NaN  
1        Series C  
2   Fresh funding  
3        Series D  
4             NaN  
..            ...  
84       Series A  
85            NaN  
86       Series B  
87            NaN  
88            NaN  

[89 rows x 5 columns]

In [3015]:
# Cleaning the Stage column 
data19['Stage'] = data19['Stage'].fillna('Unknown')
data19 

Company/Brand HeadQuarter                   Sector     Amount($)   
0    Bombay Shaving     Unknown                Ecommerce    $6,300,000  \
1         Ruangguru      Mumbai                   Edtech  $150,000,000   
2          Eduisfun      Mumbai                   Edtech   $28,000,000   
3          HomeLane     Chennai          Interior design   $30,000,000   
4          Nu Genes   Telangana                 AgriTech    $6,000,000   
..              ...         ...                      ...           ...   
84     Infra.Market      Mumbai                Infratech   $20,000,000   
85              Oyo    Gurugram              Hospitality  $693,000,000   
86       GoMechanic       Delhi  Automobile & Technology    $5,000,000   
87           Spinny       Delhi               Automobile   $50,000,000   
88  Ess Kay Fincorp   Rajasthan                  Banking   $33,000,000   

            Stage  
0         Unknown  
1        Series C  
2   Fresh funding  
3        Series D  
4         Unknown  
..            ...  
84       Series A  
85        Unknown  
86       Series B  
87        Unknown  
88        Unknown  

[89 rows x 5 columns]

Inspecting Amount Column

In [3016]:
data19['Amount($)'].value_counts()

Amount($)
Undisclosed     12
$5,000,000       6
$1,500,000       4
$6,000,000       4
$1,000,000       4
$30,000,000      3
$20,000,000      3
$50,000,000      3
$4,000,000       3
$5,500,000       3
$26,000,000      2
$2,000,000       2
$12,000,000      2
$100,000         2
$5,700,000       1
$693,000,000     1
$4,800,000       1
$120,000,000     1
$311,000,000     1
$6,800,000       1
$36,000,000      1
$2,800,000       1
$220,000         1
$600,000         1
$7,000,000       1
$2,100,000       1
$70,000,000      1
$60,000,000      1
$8,000,000       1
$25,000,000      1
$6,300,000       1
$100,000,000     1
$11,000,000      1
$28,000,000      1
$275,000,000     1
$22,000,000      1
$140,500         1
$540,000,000     1
$15,000,000      1
$182,700         1
$15,500,000      1
$400,000         1
$2,500,000       1
$140,000         1
$230,000,000     1
$49,400,000      1
$32,000,000      1
$150,000,000     1
$150,000         1
$33,000,000      1
Name: count, dtype: int64

In [3017]:
# Cleaning the amount column
# Replace currency symbol and commas with empty string
data19['Amount($)'] = data19['Amount($)'].str.replace(',', '', regex=False).str.replace('$', '', regex=False)

# Convert 'Amount' column to numeric datatype, replacing any non-numeric values.
data19['Amount($)'] = pd.to_numeric(data19['Amount($)'], errors='coerce')

# Convert Amount($) column from object to float datatype
data19['Amount($)'] = data19['Amount($)'].astype(float)

# The updated dataframe
data19.head(10)

Company/Brand HeadQuarter           Sector    Amount($)          Stage
0  Bombay Shaving     Unknown        Ecommerce   6300000.00        Unknown
1       Ruangguru      Mumbai           Edtech 150000000.00       Series C
2        Eduisfun      Mumbai           Edtech  28000000.00  Fresh funding
3        HomeLane     Chennai  Interior design  30000000.00       Series D
4        Nu Genes   Telangana         AgriTech   6000000.00        Unknown
5        FlytBase        Pune       Technology          NaN        Unknown
6           Finly   Bangalore             SaaS          NaN        Unknown
7        Kratikal       Noida       Technology   1000000.00   Pre series A
8       Quantiphi     Unknown        AI & Tech  20000000.00       Series A
9        Lenskart       Delhi       E-commerce 275000000.00       Series G

In [3018]:
# Replace NaN values in 'Amount($)' column with the mean
# Calculate the mean of Amount
median_amount = data19['Amount($)'].median()

# Replace NaN values with mean
data19['Amount($)'].fillna(median_amount, inplace=True)
data19.head(10)

Company/Brand HeadQuarter           Sector    Amount($)          Stage
0  Bombay Shaving     Unknown        Ecommerce   6300000.00        Unknown
1       Ruangguru      Mumbai           Edtech 150000000.00       Series C
2        Eduisfun      Mumbai           Edtech  28000000.00  Fresh funding
3        HomeLane     Chennai  Interior design  30000000.00       Series D
4        Nu Genes   Telangana         AgriTech   6000000.00        Unknown
5        FlytBase        Pune       Technology   6000000.00        Unknown
6           Finly   Bangalore             SaaS   6000000.00        Unknown
7        Kratikal       Noida       Technology   1000000.00   Pre series A
8       Quantiphi     Unknown        AI & Tech  20000000.00       Series A
9        Lenskart       Delhi       E-commerce 275000000.00       Series G

In [3019]:
# Check for missing values 
data19.isna().sum()

Company/Brand    0
HeadQuarter      0
Sector           0
Amount($)        0
Stage            0
dtype: int64

In [3020]:
#Inspecting stage column
data19['Stage'].unique()

array(['Unknown', 'Series C', 'Fresh funding', 'Series D', 'Pre series A',
       'Series A', 'Series G', 'Series B', 'Post series A',
       'Seed funding', 'Seed fund', 'Series E', 'Series F', 'Series B+',
       'Seed round', 'Pre-series A'], dtype=object)

In [3021]:
# Creating a year column and filling with 2019
data19.insert(0,'Year', 2019)
data19.head()

Year   Company/Brand HeadQuarter           Sector    Amount($)   
0  2019  Bombay Shaving     Unknown        Ecommerce   6300000.00  \
1  2019       Ruangguru      Mumbai           Edtech 150000000.00   
2  2019        Eduisfun      Mumbai           Edtech  28000000.00   
3  2019        HomeLane     Chennai  Interior design  30000000.00   
4  2019        Nu Genes   Telangana         AgriTech   6000000.00   

           Stage  
0        Unknown  
1       Series C  
2  Fresh funding  
3       Series D  
4        Unknown

In [3022]:
#rearrange columns to conform with other datasets
# Create a list of column names in the desired order
desired_columns = ['Year', 'Company/Brand', 'Sector', 'Amount($)', 'Stage', 'HeadQuarter']

# Reindex the DataFrame with the desired column order
data19 = data19.reindex(columns=desired_columns)

The final Cleaned 2019 DATA SET

In [3023]:
data19.head(10)

Year   Company/Brand           Sector    Amount($)          Stage   
0  2019  Bombay Shaving        Ecommerce   6300000.00        Unknown  \
1  2019       Ruangguru           Edtech 150000000.00       Series C   
2  2019        Eduisfun           Edtech  28000000.00  Fresh funding   
3  2019        HomeLane  Interior design  30000000.00       Series D   
4  2019        Nu Genes         AgriTech   6000000.00        Unknown   
5  2019        FlytBase       Technology   6000000.00        Unknown   
6  2019           Finly             SaaS   6000000.00        Unknown   
7  2019        Kratikal       Technology   1000000.00   Pre series A   
8  2019       Quantiphi        AI & Tech  20000000.00       Series A   
9  2019        Lenskart       E-commerce 275000000.00       Series G   

  HeadQuarter  
0     Unknown  
1      Mumbai  
2      Mumbai  
3     Chennai  
4   Telangana  
5        Pune  
6   Bangalore  
7       Noida  
8     Unknown  
9       Delhi

  #### 2.2.3. Cleaning 2020 Dataset

In [3024]:
#cleaning the 2020 data
data20.head(10)

Company_Brand  Founded HeadQuarter               Sector   
0    Aqgromalin  2019.00     Chennai             AgriTech  \
1      Krayonnz  2019.00   Bangalore               EdTech   
2  PadCare Labs  2018.00        Pune   Hygiene management   
3         NCOME  2020.00   New Delhi               Escrow   
4    Gramophone  2016.00      Indore             AgriTech   
5        qZense  2019.00   Bangalore             AgriTech   
6  MyClassboard  2008.00   Hyderabad               EdTech   
7         Metvy  2018.00     Gurgaon  Networking platform   
8        Rupeek  2015.00   Bangalore              FinTech   
9     Gig India  2017.00        Pune        Crowdsourcing   

                                        What_it_does   
0                       Cultivating Ideas for Profit  \
1  An academy-guardian-scholar centric ecosystem ...   
2   Converting bio-hazardous waste to harmless waste   
3                       Escrow-as-a-service platform   
4  Gramophone is an AgTech platform enabling acce...   
5  qZense Labs is building the next-generation Io...   
6  MyClassboard is a full-fledged School / Colleg...   
7  AI driven networking platform for individuals ...   
8  Rupeek is an online lending platform that spec...   
9  GigIndia is a marketplace that provides on-dem...   

                                            Founders   
0                    Prasanna Manogaran, Bharani C L  \
1                   Saurabh Dixit, Gurudutt Upadhyay   
2                                    Ajinkya Dhariya   
3                                      Ritesh Tiwari   
4  Ashish Rajan Singh, Harshit Gupta, Nishant Mah...   
5                       Rubal Chib, Dr Srishti Batra   
6                                     Ajay Sakhamuri   
7                                   Shawrya Mehrotra   
8            Amar Prabhu, Ashwin Soni, Sumit Maniyar   
9                       Aditya Shirole, Sahil Sharma   

                                        Investor      Amount         Stage   
0                                Angel investors   200000.00          None  \
1                                GSF Accelerator   100000.00      Pre-seed   
2                                 Venture Center         NaN      Pre-seed   
3            Venture Catalysts, PointOne Capital   400000.00          None   
4            Siana Capital Management, Info Edge   340000.00          None   
5  Venture Catalysts, 9Unicorns Accelerator Fund   600000.00          Seed   
6                                    ICICI Bank.   600000.00  Pre-series A   
7                                     HostelFund         NaN    Pre-series   
8   KB Investment, Bertelsmann India Investments 45000000.00      Series C   
9      Shantanu Deshpande, Subramaniam Ramadorai  1000000.00  Pre-series A   

  column10  
0     None  
1     None  
2     None  
3     None  
4     None  
5     None  
6     None  
7     None  
8     None  
9     None

In [3025]:
## check for Data Types
data20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1055 entries, 0 to 1054
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Company_Brand  1055 non-null   object 
 1   Founded        842 non-null    float64
 2   HeadQuarter    961 non-null    object 
 3   Sector         1042 non-null   object 
 4   What_it_does   1055 non-null   object 
 5   Founders       1043 non-null   object 
 6   Investor       1017 non-null   object 
 7   Amount         801 non-null    float64
 8   Stage          591 non-null    object 
 9   column10       2 non-null      object 
dtypes: float64(2), object(8)
memory usage: 82.5+ KB


In [3026]:
# Check for shape of the data
data20.shape

(1055, 10)

The data 2020 has 10 columns, where by two of the columns contains float entries and 8 others contains object entries

 I. Drop columns not needed for analysis

In [3027]:
#drop column 10,founders,investor,what it does,Founded, since it is needed for analysis
data20 = data20.drop('column10', axis=1)
data20 = data20.drop('Founders', axis=1)
data20 = data20.drop('Investor', axis = 1)
data20 = data20.drop('What_it_does', axis = 1)
data20 = data20.drop('Founded',axis = 1)

In [3028]:
data20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1055 entries, 0 to 1054
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Company_Brand  1055 non-null   object 
 1   HeadQuarter    961 non-null    object 
 2   Sector         1042 non-null   object 
 3   Amount         801 non-null    float64
 4   Stage          591 non-null    object 
dtypes: float64(1), object(4)
memory usage: 41.3+ KB


The unnecessary columns have been dropped and now we have 5 columns left. Lets rename the columns to match with 2018 and 2019 data

In [3029]:
#rename column names to make it consistent with the other data set
data20.rename(columns={'Company_Brand' : 'Company/Brand'}, inplace = True)

In [3030]:
#The updated Dataframe for 2020
data20.head(10)

Company/Brand HeadQuarter               Sector      Amount         Stage
0    Aqgromalin     Chennai             AgriTech   200000.00          None
1      Krayonnz   Bangalore               EdTech   100000.00      Pre-seed
2  PadCare Labs        Pune   Hygiene management         NaN      Pre-seed
3         NCOME   New Delhi               Escrow   400000.00          None
4    Gramophone      Indore             AgriTech   340000.00          None
5        qZense   Bangalore             AgriTech   600000.00          Seed
6  MyClassboard   Hyderabad               EdTech   600000.00  Pre-series A
7         Metvy     Gurgaon  Networking platform         NaN    Pre-series
8        Rupeek   Bangalore              FinTech 45000000.00      Series C
9     Gig India        Pune        Crowdsourcing  1000000.00  Pre-series A

 II. Check for duplicates in the data set

In [3031]:
#check for duplicates in the data20
duplicates = data20.duplicated(keep=False)

#returns the total number of duplicates
duplicates_count = duplicates.value_counts()
duplicates_count

False    1043
True       12
Name: count, dtype: int64

In [3032]:
#identify docuplicated rows
duplicates = data20[data20.duplicated(keep=False)]
duplicates

Company/Brand HeadQuarter                 Sector       Amount Stage
120            Nykaa      Mumbai              Cosmetics          NaN  None
129        Krimanshi     Jodhpur  Biotechnology company    600000.00  Seed
145        Krimanshi     Jodhpur  Biotechnology company    600000.00  Seed
205            Nykaa      Mumbai              Cosmetics          NaN  None
215   Genius Teacher      Mumbai                 Edtech   2000000.00  None
233   Genius Teacher      Mumbai                 Edtech   2000000.00  None
326           Byju’s   Bangalore                 EdTech 500000000.00  None
362           Byju’s   Bangalore                 EdTech 500000000.00  None
771    Capital Float   Bangalore                Fintech  15000000.00  None
935             Byju        None                 Edtech 200000000.00  None
1014   Capital Float   Bangalore                Fintech  15000000.00  None
1035            Byju        None                 Edtech 200000000.00  None

In [3033]:
#There are 12 duplicated rows
#drop duplicated rows
data20.drop_duplicates(keep='first', inplace= True)

In [3034]:
#check if duplicates have been dropped
duplicates = data20[data20.duplicated(keep=False)]
duplicates

Empty DataFrame
Columns: [Company/Brand, HeadQuarter, Sector, Amount, Stage]
Index: []

III. Check for missing values

In [3035]:
#checking for missing values in Data20
missing_values_data20 = data20.isnull().sum()
missing_values_data20

Company/Brand      0
HeadQuarter       93
Sector            13
Amount           253
Stage            459
dtype: int64

Handling Missing values columnwise- inspecting sector column


In [3036]:
## Inspect the company column,
data20['Sector'].value_counts()

Sector
Fintech                  79
Edtech                   65
FinTech                  51
EdTech                   39
E-commerce               33
                         ..
Jewellery                 1
AR startup                1
HR Tech startup           1
Automotive Startup        1
Automobile Technology     1
Name: count, Length: 302, dtype: int64

In [3037]:
#replace missing values in 'Sector' column with 'Unknown'
data20['Sector'] = data20['Sector'].fillna('Unknown')
data20.head(10)

Company/Brand HeadQuarter               Sector      Amount         Stage
0    Aqgromalin     Chennai             AgriTech   200000.00          None
1      Krayonnz   Bangalore               EdTech   100000.00      Pre-seed
2  PadCare Labs        Pune   Hygiene management         NaN      Pre-seed
3         NCOME   New Delhi               Escrow   400000.00          None
4    Gramophone      Indore             AgriTech   340000.00          None
5        qZense   Bangalore             AgriTech   600000.00          Seed
6  MyClassboard   Hyderabad               EdTech   600000.00  Pre-series A
7         Metvy     Gurgaon  Networking platform         NaN    Pre-series
8        Rupeek   Bangalore              FinTech 45000000.00      Series C
9     Gig India        Pune        Crowdsourcing  1000000.00  Pre-series A

Inspecting the Amount column

In [3038]:
## Inspect the company column,
data20['Amount'].unique()

array([2.0000000e+05, 1.0000000e+05,           nan, 4.0000000e+05,
       3.4000000e+05, 6.0000000e+05, 4.5000000e+07, 1.0000000e+06,
       2.0000000e+06, 1.2000000e+06, 6.6000000e+08, 1.2000000e+05,
       7.5000000e+06, 5.0000000e+06, 5.0000000e+05, 3.0000000e+06,
       1.0000000e+07, 1.4500000e+08, 1.0000000e+08, 2.1000000e+07,
       4.0000000e+06, 2.0000000e+07, 5.6000000e+05, 2.7500000e+05,
       4.5000000e+06, 1.5000000e+07, 3.9000000e+08, 7.0000000e+06,
       5.1000000e+06, 7.0000000e+08, 2.3000000e+06, 7.0000000e+05,
       1.9000000e+07, 9.0000000e+06, 4.0000000e+07, 7.5000000e+05,
       1.5000000e+06, 7.8000000e+06, 5.0000000e+07, 8.0000000e+07,
       3.0000000e+07, 1.7000000e+06, 2.5000000e+06, 4.0000000e+04,
       3.3000000e+07, 3.5000000e+07, 3.0000000e+05, 2.5000000e+07,
       3.5000000e+06, 2.0000000e+08, 6.0000000e+06, 1.3000000e+06,
       4.1000000e+06, 5.7500000e+05, 8.0000000e+05, 2.8000000e+07,
       1.8000000e+07, 3.2000000e+06, 9.0000000e+05, 2.5000000e

In [3039]:
#It is assumed that the amounts are already in dollars.
#Rename 'Amount' column to 'Amount($)'
data20.rename(columns={'Amount' : 'Amount($)'}, inplace= True)
data20

Company/Brand HeadQuarter              Sector   Amount($)       Stage
0       Aqgromalin     Chennai            AgriTech   200000.00        None
1         Krayonnz   Bangalore              EdTech   100000.00    Pre-seed
2     PadCare Labs        Pune  Hygiene management         NaN    Pre-seed
3            NCOME   New Delhi              Escrow   400000.00        None
4       Gramophone      Indore            AgriTech   340000.00        None
...            ...         ...                 ...         ...         ...
1050  Leverage Edu       Delhi              Edtech  1500000.00        None
1051         EpiFi        None             Fintech 13200000.00  Seed Round
1052       Purplle      Mumbai           Cosmetics  8000000.00        None
1053        Shuttl       Delhi           Transport  8043000.00    Series C
1054         Pando     Chennai            Logitech  9000000.00    Series A

[1049 rows x 5 columns]

In [3040]:
#calculate mean of the 'Amount($)' column 
#Replace missing values in 'Amount($)' column with the median
median_value = data20['Amount($)'].median()

data20['Amount($)'].fillna(value = median_value,  inplace=True)

data20

Company/Brand HeadQuarter              Sector   Amount($)       Stage
0       Aqgromalin     Chennai            AgriTech   200000.00        None
1         Krayonnz   Bangalore              EdTech   100000.00    Pre-seed
2     PadCare Labs        Pune  Hygiene management  3000000.00    Pre-seed
3            NCOME   New Delhi              Escrow   400000.00        None
4       Gramophone      Indore            AgriTech   340000.00        None
...            ...         ...                 ...         ...         ...
1050  Leverage Edu       Delhi              Edtech  1500000.00        None
1051         EpiFi        None             Fintech 13200000.00  Seed Round
1052       Purplle      Mumbai           Cosmetics  8000000.00        None
1053        Shuttl       Delhi           Transport  8043000.00    Series C
1054         Pando     Chennai            Logitech  9000000.00    Series A

[1049 rows x 5 columns]

Inspecting Stage column to check abnormly

In [3041]:
## Inspect the company column,
data20['Stage'].unique()

array([None, 'Pre-seed', 'Seed', 'Pre-series A', 'Pre-series', 'Series C',
       'Series A', 'Series B', 'Debt', 'Pre-series C', 'Pre-series B',
       'Series E', 'Bridge', 'Series D', 'Series B2', 'Series F',
       'Pre- series A', 'Edge', 'Series H', 'Pre-Series B', 'Seed A',
       'Series A-1', 'Seed Funding', 'Pre-Seed', 'Seed round',
       'Pre-seed Round', 'Seed Round & Series A', 'Pre Series A',
       'Pre seed Round', 'Angel Round', 'Pre series A1', 'Series E2',
       'Pre series A', 'Seed Round', 'Bridge Round', 'Pre seed round',
       'Pre series B', 'Pre series C', 'Seed Investment', 'Series D1',
       'Mid series', 'Series C, D', 'Seed funding'], dtype=object)

In [3042]:
#fill in the missing values in the 'Stage' column with 'unknown'
data20['Stage'] = data20['Stage'].fillna('Unknown')
data20.head(10)

Company/Brand HeadQuarter               Sector   Amount($)         Stage
0    Aqgromalin     Chennai             AgriTech   200000.00       Unknown
1      Krayonnz   Bangalore               EdTech   100000.00      Pre-seed
2  PadCare Labs        Pune   Hygiene management  3000000.00      Pre-seed
3         NCOME   New Delhi               Escrow   400000.00       Unknown
4    Gramophone      Indore             AgriTech   340000.00       Unknown
5        qZense   Bangalore             AgriTech   600000.00          Seed
6  MyClassboard   Hyderabad               EdTech   600000.00  Pre-series A
7         Metvy     Gurgaon  Networking platform  3000000.00    Pre-series
8        Rupeek   Bangalore              FinTech 45000000.00      Series C
9     Gig India        Pune        Crowdsourcing  1000000.00  Pre-series A

IV. Inspecting  columns for anomaly

In [3043]:
#Inspect the HeadQuarter column,
data20['HeadQuarter'].unique()

array(['Chennai', 'Bangalore', 'Pune', 'New Delhi', 'Indore', 'Hyderabad',
       'Gurgaon', 'Belgaum', 'Noida', 'Mumbai', 'Andheri', 'Jaipur',
       'Ahmedabad', 'Kolkata', 'Tirunelveli, Tamilnadu', 'Thane', None,
       'Singapore', 'Gurugram', 'Gujarat', 'Haryana', 'Kerala', 'Jodhpur',
       'Jaipur, Rajastan', 'Delhi', 'Frisco, Texas, United States',
       'California', 'Dhingsara, Haryana', 'New York, United States',
       'Patna', 'San Francisco, California, United States',
       'San Francisco, United States', 'San Ramon, California',
       'Paris, Ile-de-France, France', 'Plano, Texas, United States',
       'Sydney', 'San Francisco Bay Area, Silicon Valley, West Coast',
       'Bangaldesh', 'London, England, United Kingdom',
       'Sydney, New South Wales, Australia', 'Milano, Lombardia, Italy',
       'Palmwoods, Queensland, Australia', 'France',
       'San Francisco Bay Area, West Coast, Western US',
       'Trivandrum, Kerala, India', 'Cochin', 'Samastipur, Bihar',


In [3044]:
data20[["City", "State", "Country"]]= data20['HeadQuarter'].str.split(',', expand=True)
data20.tail(30)

Company/Brand HeadQuarter                 Sector    Amount($)   
1024  Harappa Education   New Delhi                 Edtech   3000000.00  \
1025               Rheo        None          Entertainment   2000000.00   
1026  Axio Biosolutions   Bangalore                Medtech   5200000.00   
1027          Techbooze        None            Consultancy  15000000.00   
1028            PayMart  Chandigarh                Fintech   3000000.00   
1029           Testbook        None                 Edtech   8400000.00   
1030           FabAlley       Noida              Ecommerce   1100000.00   
1031           HaikuJAM        None                Unknown   3400000.00   
1032          Mamaearth        None              Ecommerce  18300000.00   
1033          Rentomojo        None                 Rental   2000000.00   
1034             Zomato        None               Foodtech 150000000.00   
1036           Generico      Mumbai               Pharmacy   1400000.00   
1037         HighRadius   Hyderabad                   SaaS 125000000.00   
1038         Chai Kings     Chennai               Beverage   1000000.00   
1039             Rivigo    Gurugram              Logistics   3400000.00   
1040           BuildPan      Indore                   SaaS   3000000.00   
1041            Shiksha        None                 Edtech    181000.00   
1042     Super Surfaces   Hyderabad              Deisgning    500000.00   
1043             Quicko   Ahmedabad               Taxation    280000.00   
1044   Satin Creditcare     Gurgaon                Fintech  15000000.00   
1045         XpressBees        None              Logistics  10000000.00   
1046            FarmERP        Pune               Agritech   3000000.00   
1047      Wealth Bucket        None                Fintech   3000000.00   
1048         GoMechanic       Delhi  Automobile Technology  14700000.00   
1049             Fashor     Chennai                Fashion   1000000.00   
1050       Leverage Edu       Delhi                 Edtech   1500000.00   
1051              EpiFi        None                Fintech  13200000.00   
1052            Purplle      Mumbai              Cosmetics   8000000.00   
1053             Shuttl       Delhi              Transport   8043000.00   
1054              Pando     Chennai               Logitech   9000000.00   

             Stage        City State Country  
1024       Unknown   New Delhi  None    None  
1025       Unknown        None  None    None  
1026      Series B   Bangalore  None    None  
1027      Series A        None  None    None  
1028       Unknown  Chandigarh  None    None  
1029      Series B        None  None    None  
1030       Unknown       Noida  None    None  
1031       Unknown        None  None    None  
1032      Series A        None  None    None  
1033       Unknown        None  None    None  
1034       Unknown        None  None    None  
1036       Unknown      Mumbai  None    None  
1037      Series B   Hyderabad  None    None  
1038       Unknown     Chennai  None    None  
1039      Series F    Gurugram  None    None  
1040    Seed Round      Indore  None    None  
1041       Unknown        None  None    None  
1042      Series A   Hyderabad  None    None  
1043       Unknown   Ahmedabad  None    None  
1044       Unknown     Gurgaon  None    None  
1045       Unknown        None  None    None  
1046      Series A        Pune  None    None  
1047       Unknown        None  None    None  
1048      Series B       Delhi  None    None  
1049  Pre Series A     Chennai  None    None  
1050       Unknown       Delhi  None    None  
1051    Seed Round        None  None    None  
1052       Unknown      Mumbai  None    None  
1053      Series C       Delhi  None    None  
1054      Series A     Chennai  None    None

In [3045]:
data20['State'].unique()

array([None, ' Tamilnadu', ' Rajastan', ' Texas', ' Haryana',
       ' United States', ' California', ' Ile-de-France',
       ' Silicon Valley', ' England', ' New South Wales', ' Lombardia',
       ' Queensland', ' West Coast', ' Kerala', ' Bihar', ' Karnataka',
       ' Newcastle upon Tyne', ' China', ' Zhejiang', ' Jawa Barat'],
      dtype=object)

In [3046]:
# Drop Columns named - State Country and Hedquater then name city headquater

data20.drop('Country',axis = 1,inplace = True)
data20.drop('State',axis = 1,inplace = True)
data20.drop('HeadQuarter',axis = 1,inplace = True)
data20.head()

Company/Brand              Sector  Amount($)     Stage       City
0    Aqgromalin            AgriTech  200000.00   Unknown    Chennai
1      Krayonnz              EdTech  100000.00  Pre-seed  Bangalore
2  PadCare Labs  Hygiene management 3000000.00  Pre-seed       Pune
3         NCOME              Escrow  400000.00   Unknown  New Delhi
4    Gramophone            AgriTech  340000.00   Unknown     Indore

In [3047]:
#replace missing values in 'Location' column with 'Unknown'
data20['City'] = data20['City'].fillna('Unknown')
data20.tail(20)

Company/Brand                 Sector    Amount($)         Stage   
1034            Zomato               Foodtech 150000000.00       Unknown  \
1036          Generico               Pharmacy   1400000.00       Unknown   
1037        HighRadius                   SaaS 125000000.00      Series B   
1038        Chai Kings               Beverage   1000000.00       Unknown   
1039            Rivigo              Logistics   3400000.00      Series F   
1040          BuildPan                   SaaS   3000000.00    Seed Round   
1041           Shiksha                 Edtech    181000.00       Unknown   
1042    Super Surfaces              Deisgning    500000.00      Series A   
1043            Quicko               Taxation    280000.00       Unknown   
1044  Satin Creditcare                Fintech  15000000.00       Unknown   
1045        XpressBees              Logistics  10000000.00       Unknown   
1046           FarmERP               Agritech   3000000.00      Series A   
1047     Wealth Bucket                Fintech   3000000.00       Unknown   
1048        GoMechanic  Automobile Technology  14700000.00      Series B   
1049            Fashor                Fashion   1000000.00  Pre Series A   
1050      Leverage Edu                 Edtech   1500000.00       Unknown   
1051             EpiFi                Fintech  13200000.00    Seed Round   
1052           Purplle              Cosmetics   8000000.00       Unknown   
1053            Shuttl              Transport   8043000.00      Series C   
1054             Pando               Logitech   9000000.00      Series A   

           City  
1034    Unknown  
1036     Mumbai  
1037  Hyderabad  
1038    Chennai  
1039   Gurugram  
1040     Indore  
1041    Unknown  
1042  Hyderabad  
1043  Ahmedabad  
1044    Gurgaon  
1045    Unknown  
1046       Pune  
1047    Unknown  
1048      Delhi  
1049    Chennai  
1050      Delhi  
1051    Unknown  
1052     Mumbai  
1053      Delhi  
1054    Chennai

In [3048]:
# Rename City column to Headquarter
data20.rename(columns={'City':'HeadQuarter'}, inplace=True)

Confirm if missing values have been resolved

In [3049]:
#check for missing values
data20.isna().sum()

Company/Brand    0
Sector           0
Amount($)        0
Stage            0
HeadQuarter      0
dtype: int64

In [3050]:
## Inspect the company column,
data20['HeadQuarter'].unique()

array(['Chennai', 'Bangalore', 'Pune', 'New Delhi', 'Indore', 'Hyderabad',
       'Gurgaon', 'Belgaum', 'Noida', 'Mumbai', 'Andheri', 'Jaipur',
       'Ahmedabad', 'Kolkata', 'Tirunelveli', 'Thane', 'Unknown',
       'Singapore', 'Gurugram', 'Gujarat', 'Haryana', 'Kerala', 'Jodhpur',
       'Delhi', 'Frisco', 'California', 'Dhingsara', 'New York', 'Patna',
       'San Francisco', 'San Ramon', 'Paris', 'Plano', 'Sydney',
       'San Francisco Bay Area', 'Bangaldesh', 'London', 'Milano',
       'Palmwoods', 'France', 'Trivandrum', 'Cochin', 'Samastipur',
       'Irvine', 'Tumkur', 'Newcastle Upon Tyne', 'Shanghai', 'Jiaxing',
       'Rajastan', 'Kochi', 'Ludhiana', 'Dehradun', 'San Franciscao',
       'Tangerang', 'Berlin', 'Seattle', 'Riyadh', 'Seoul', 'Bangkok',
       'Kanpur', 'Chandigarh', 'Warangal', 'Hyderebad', 'Odisha', 'Bihar',
       'Goa', 'Tamil Nadu', 'Uttar Pradesh', 'Bhopal', 'Banglore',
       'Coimbatore', 'Bengaluru'], dtype=object)

In [3051]:
#Renaming Some od Headquarter Entries
data20['HeadQuarter'] = data20['HeadQuarter'].str.replace('Banglore','Bengaluru', case=False)

In [3052]:
data20['HeadQuarter'].unique()

array(['Chennai', 'Bangalore', 'Pune', 'New Delhi', 'Indore', 'Hyderabad',
       'Gurgaon', 'Belgaum', 'Noida', 'Mumbai', 'Andheri', 'Jaipur',
       'Ahmedabad', 'Kolkata', 'Tirunelveli', 'Thane', 'Unknown',
       'Singapore', 'Gurugram', 'Gujarat', 'Haryana', 'Kerala', 'Jodhpur',
       'Delhi', 'Frisco', 'California', 'Dhingsara', 'New York', 'Patna',
       'San Francisco', 'San Ramon', 'Paris', 'Plano', 'Sydney',
       'San Francisco Bay Area', 'Bangaldesh', 'London', 'Milano',
       'Palmwoods', 'France', 'Trivandrum', 'Cochin', 'Samastipur',
       'Irvine', 'Tumkur', 'Newcastle Upon Tyne', 'Shanghai', 'Jiaxing',
       'Rajastan', 'Kochi', 'Ludhiana', 'Dehradun', 'San Franciscao',
       'Tangerang', 'Berlin', 'Seattle', 'Riyadh', 'Seoul', 'Bangkok',
       'Kanpur', 'Chandigarh', 'Warangal', 'Hyderebad', 'Odisha', 'Bihar',
       'Goa', 'Tamil Nadu', 'Uttar Pradesh', 'Bhopal', 'Bengaluru',
       'Coimbatore'], dtype=object)

In [3053]:
data20.head()

Company/Brand              Sector  Amount($)     Stage HeadQuarter
0    Aqgromalin            AgriTech  200000.00   Unknown     Chennai
1      Krayonnz              EdTech  100000.00  Pre-seed   Bangalore
2  PadCare Labs  Hygiene management 3000000.00  Pre-seed        Pune
3         NCOME              Escrow  400000.00   Unknown   New Delhi
4    Gramophone            AgriTech  340000.00   Unknown      Indore

In [3054]:
# Creating a year column and filling with 2018
data20.insert(0,'Year', 2020)
data20.head()

Year Company/Brand              Sector  Amount($)     Stage HeadQuarter
0  2020    Aqgromalin            AgriTech  200000.00   Unknown     Chennai
1  2020      Krayonnz              EdTech  100000.00  Pre-seed   Bangalore
2  2020  PadCare Labs  Hygiene management 3000000.00  Pre-seed        Pune
3  2020         NCOME              Escrow  400000.00   Unknown   New Delhi
4  2020    Gramophone            AgriTech  340000.00   Unknown      Indore

The Final Cleaned 2020 DataSet

In [3055]:
data20.head()

Year Company/Brand              Sector  Amount($)     Stage HeadQuarter
0  2020    Aqgromalin            AgriTech  200000.00   Unknown     Chennai
1  2020      Krayonnz              EdTech  100000.00  Pre-seed   Bangalore
2  2020  PadCare Labs  Hygiene management 3000000.00  Pre-seed        Pune
3  2020         NCOME              Escrow  400000.00   Unknown   New Delhi
4  2020    Gramophone            AgriTech  340000.00   Unknown      Indore

## 2.2.4. Cleaning 2021 Dataset

In [3056]:
data21.head(10)

Company_Brand  Founded HeadQuarter          Sector   
0  Unbox Robotics  2019.00   Bangalore      AI startup  \
1          upGrad  2015.00      Mumbai          EdTech   
2     Lead School  2012.00      Mumbai          EdTech   
3         Bizongo  2015.00      Mumbai  B2B E-commerce   
4        FypMoney  2021.00    Gurugram         FinTech   
5   Urban Company  2014.00   New Delhi   Home services   
6  Comofi Medtech  2018.00   Bangalore      HealthTech   
7     Qube Health  2016.00      Mumbai      HealthTech   
8        Vitra.ai  2020.00   Bangalore    Tech Startup   
9          Taikee  2010.00      Mumbai      E-commerce   

                                        What_it_does   
0  Unbox Robotics builds on-demand AI-driven ware...  \
1     UpGrad is an online higher education platform.   
2  LEAD School offers technology based school tra...   
3  Bizongo is a business-to-business online marke...   
4  FypMoney is Digital NEO Bank for Teenagers, em...   
5  Urban Company (Formerly UrbanClap) is a home a...   
6   Comofi Medtech is a healthcare robotics startup.   
7  India's Most Respected Workplace Healthcare Ma...   
8  Vitra.ai is an AI-based video translation plat...   
9  Taikee is the ISO-certified, B2B e-commerce pl...   

                                            Founders   
0                        Pramod Ghadge, Shahid Memon  \
1  Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...   
2                         Smita Deorah, Sumeet Mehta   
3            Aniket Deb, Ankit Tomar, Sachin Agrawal   
4                                      Kapil Banwari   
5  Abhiraj Singh Bhal, Raghav Chandra, Varun Khaitan   
6                                         Gururaj KB   
7                                        Gagan Kapur   
8                                     Akash Nidhi PS   
9                 Nidhi Ramachandran, Sachin Chhabra   

                                        Investor        Amount         Stage  
0                    BEENEXT, Entrepreneur First    $1,200,000  Pre-series A  
1       Unilazer Ventures, IIFL Asset Management  $120,000,000          None  
2               GSV Ventures, Westbridge Capital   $30,000,000      Series D  
3                         CDC Group, IDG Capital   $51,000,000      Series C  
4  Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal    $2,000,000          Seed  
5                                     Vy Capital  $188,000,000          None  
6                              CIIE.CO, KIIT-TBI      $200,000          None  
7                      Inflection Point Ventures   Undisclosed  Pre-series A  
8                              Inflexor Ventures   Undisclosed          None  
9                                           None    $1,000,000          None

Cleaning data Column Wise

In [3057]:
# Checking for data types
data21.dtypes

Company_Brand     object
Founded          float64
HeadQuarter       object
Sector            object
What_it_does      object
Founders          object
Investor          object
Amount            object
Stage             object
dtype: object

one column is float, we need to convert amount column to float

I. DROP COLUMNS NOT NEEDED FOR ANALYSIS, TO MATCH ALL THE DATASETS
i.e Founder, Founded, What it does and Investor

In [3058]:
data21.columns

Index(['Company_Brand', 'Founded', 'HeadQuarter', 'Sector', 'What_it_does',
       'Founders', 'Investor', 'Amount', 'Stage'],
      dtype='object')

In [3059]:
columndrop = ['Founded', 'Founders', 'What_it_does', 'Investor']
data21.drop(columndrop, axis=1, inplace=True)


In [3060]:
data21.head()

Company_Brand HeadQuarter          Sector        Amount         Stage
0  Unbox Robotics   Bangalore      AI startup    $1,200,000  Pre-series A
1          upGrad      Mumbai          EdTech  $120,000,000          None
2     Lead School      Mumbai          EdTech   $30,000,000      Series D
3         Bizongo      Mumbai  B2B E-commerce   $51,000,000      Series C
4        FypMoney    Gurugram         FinTech    $2,000,000          Seed

In [3061]:
#rename column names to make it consistent with the other data set
data21.rename(columns={'Company_Brand' : 'Company/Brand'}, inplace = True)
data21.rename(columns= {'Amount': 'Amount($)'}, inplace = True)

II. Check for duplicates

In [3062]:
#check for duplicates in the data20
duplicates = data21.duplicated(keep=False)

#returns the total number of duplicates
duplicates_count = duplicates.value_counts()
duplicates_count

False    1165
True       44
Name: count, dtype: int64

We have 44 duplicates in the data 2021

In [3063]:
#identify docuplicated rows
duplicates = data21[data21.duplicated(keep=False)]
duplicates

Company/Brand             HeadQuarter   
94             Curefoods               Bangalore  \
96              Bewakoof                  Mumbai   
98               FanPlay          Computer Games   
104       Advantage Club                  Mumbai   
106               Ruptok               New Delhi   
107            Curefoods               Bangalore   
109             Bewakoof                  Mumbai   
111              FanPlay          Computer Games   
117       Advantage Club                  Mumbai   
119               Ruptok               New Delhi   
229             Trinkerr               Bangalore   
230                Zorro                Gurugram   
231        Ultraviolette               Bangalore   
232           NephroPlus               Hyderabad   
233              Unremot               Bangalore   
234          FanAnywhere               Bangalore   
235           PingoLearn                    Pune   
236                 Spry                  Mumbai   
237              Enmovil               Hyderabad   
238        ASQI Advisors                  Mumbai   
239   Insurance Samadhan               New Delhi   
240      Evenflow Brands                  Mumbai   
241           MasterChow        Food & Beverages   
242   Fullife Healthcare  Pharmaceuticals\t#REF!   
243             Trinkerr               Bangalore   
244                Zorro                Gurugram   
245        Ultraviolette               Bangalore   
246           NephroPlus               Hyderabad   
247              Unremot               Bangalore   
248          FanAnywhere               Bangalore   
249           PingoLearn                    Pune   
250                 Spry                  Mumbai   
251              Enmovil               Hyderabad   
252        ASQI Advisors                  Mumbai   
253   Insurance Samadhan               New Delhi   
254      Evenflow Brands                  Mumbai   
255           MasterChow        Food & Beverages   
256   Fullife Healthcare  Pharmaceuticals\t#REF!   
351                Siply               Bangalore   
401             BharatPe               New Delhi   
416                Siply               Bangalore   
847             BharatPe               New Delhi   
973         Ola Electric               Bangalore   
1076        Ola Electric               Bangalore   

                                                 Sector     Amount($)   
94                                     Food & Beverages     $13000000  \
96                                    Apparel & Fashion      $8000000   
98                                       Computer Games      Upsparks   
104                                              HRTech      $1700000   
106                                             FinTech      $1000000   
107                                    Food & Beverages     $13000000   
109                                   Apparel & Fashion      $8000000   
111                                      Computer Games      Upsparks   
117                                              HRTech      $1700000   
119                                             FinTech      $1000000   
229                                     Capital Markets      $6600000   
230                                      Social network     $32000000   
231                                          Automotive    $150000000   
232                              Hospital & Health Care     $24000000   
233                   Information Technology & Services       $700000   
234                                  Financial Services  $Undisclosed   
235                                          E-learning       $200000   
236                                               Music      $1500000   
237                   Information Technology & Services      $1300000   
238                                  Financial Services      $1000000   
239                                           Insurance       $725000   
240                                      Consumer Goods       $5

In [3064]:
#There are 44 duplicated rows
#drop duplicated rows
data21.drop_duplicates(keep='first', inplace= True)

In [3065]:
#check if duplicates have been dropped
duplicates = data21[data21.duplicated(keep=False)]
duplicates

Empty DataFrame
Columns: [Company/Brand, HeadQuarter, Sector, Amount($), Stage]
Index: []

All the dupicated rows have been dropped.

III. Check missing values

In [3066]:
data21.isnull().sum()

Company/Brand      0
HeadQuarter        1
Sector             0
Amount($)          3
Stage            420
dtype: int64

We have one missing value in Headquarter, Amounts - 3 and Stage column have 420. We have to fill the missing values in the each column seperately.

#### We can see that there are few missing values. But missing values can be represented using '-', let's check 

In [3067]:
# Replacing '-' with NaN
data21.replace("—", np.nan, inplace=True)

# Check for missing values
missing_values_data21 = data21.isnull().sum()
missing_values_data21

Company/Brand      0
HeadQuarter        1
Sector             0
Amount($)          3
Stage            420
dtype: int64

Its justified that this are the only missing values

In [3068]:
# Dealing with Missing Values in Headquarter column fill in with unknown
data21['HeadQuarter'] = data20['HeadQuarter'].fillna('Unknown')
data21.head(10)

Company/Brand HeadQuarter          Sector     Amount($)         Stage
0  Unbox Robotics     Chennai      AI startup    $1,200,000  Pre-series A
1          upGrad   Bangalore          EdTech  $120,000,000          None
2     Lead School        Pune          EdTech   $30,000,000      Series D
3         Bizongo   New Delhi  B2B E-commerce   $51,000,000      Series C
4        FypMoney      Indore         FinTech    $2,000,000          Seed
5   Urban Company   Bangalore   Home services  $188,000,000          None
6  Comofi Medtech   Hyderabad      HealthTech      $200,000          None
7     Qube Health     Gurgaon      HealthTech   Undisclosed  Pre-series A
8        Vitra.ai   Bangalore    Tech Startup   Undisclosed          None
9          Taikee        Pune      E-commerce    $1,000,000          None

In [3069]:
data21['HeadQuarter'].value_counts

<bound method IndexOpsMixin.value_counts of 0         Chennai
1       Bangalore
2            Pune
3       New Delhi
4          Indore
          ...    
1204          NaN
1205          NaN
1206          NaN
1207          NaN
1208          NaN
Name: HeadQuarter, Length: 1187, dtype: object>

We have NaN in the Headquarter Column. Lets convert the values to strings and check if still have missing values

In [3070]:
data21['HeadQuarter'] = data21['HeadQuarter'].astype(str)

In [3071]:
data21['HeadQuarter'].value_counts()

HeadQuarter
Bangalore              309
Mumbai                 160
nan                    159
Unknown                 93
Gurugram                74
                      ... 
Newcastle Upon Tyne      1
Shanghai                 1
Jiaxing                  1
Rajastan                 1
Coimbatore               1
Name: count, Length: 71, dtype: int64

In [3072]:
data21['HeadQuarter'].isna().sum()

0

The misisng Values in Headquarter Column has been handled.

The amount column needs cleaning before filling the missing values with the median value

In [3073]:
# Replacing the missing values in Amount columns with median value
# Replace '$' currency symbol and commas with empty string
data21['Amount($)'] = data21['Amount($)'].str.replace(',', '', regex=False).str.replace('$', '', regex=False)
data21

Company/Brand HeadQuarter                 Sector  Amount($)   
0     Unbox Robotics     Chennai             AI startup    1200000  \
1             upGrad   Bangalore                 EdTech  120000000   
2        Lead School        Pune                 EdTech   30000000   
3            Bizongo   New Delhi         B2B E-commerce   51000000   
4           FypMoney      Indore                FinTech    2000000   
...              ...         ...                    ...        ...   
1204        Gigforce         nan  Staffing & Recruiting    3000000   
1205          Vahdam         nan       Food & Beverages   20000000   
1206    Leap Finance         nan     Financial Services   55000000   
1207    CollegeDekho         nan                 EdTech   26000000   
1208          WeRize         nan     Financial Services    8000000   

             Stage  
0     Pre-series A  
1             None  
2         Series D  
3         Series C  
4             Seed  
...            ...  
1204  Pre-series A  
1205      Series D  
1206      Series C  
1207      Series B  
1208      Series A  

[1187 rows x 5 columns]

In [3074]:
data21['Amount($)'].value_counts()

Amount($)
Undisclosed    115
1000000         82
2000000         60
3000000         48
10000000        43
              ... 
67000000         1
36000000         1
Upsparks         1
720000           1
55000000         1
Name: count, Length: 207, dtype: int64

The amount column has non numerical entried. Lets check them.

In [3075]:
# Convert the Amount Column to numeric with errors='coerce'
data21['Amount($)'] = pd.to_numeric(data21['Amount($)'], errors='coerce')
# Convert Amount($) column from object to float datatype
data21['Amount($)'] = data21['Amount($)'].astype(float)

# Check for non-numeric values
non_numeric_values = data21['Amount($)'][numeric_column.isna()]

# Print the non-numeric values
print(non_numeric_values)

7      NaN
8      NaN
21     NaN
39     NaN
54     NaN
        ..
1148   NaN
1160   NaN
1161   NaN
1166   NaN
1193   NaN
Name: Amount($), Length: 150, dtype: float64


The non numeric entries are 150 in number. and have been converted to numeric NaN. Lets check missing values again in the amount column Lets now fill the missing values with the median value.

In [3076]:
data21['Amount($)'].unique()

array([1.20e+06, 1.20e+08, 3.00e+07, 5.10e+07, 2.00e+06, 1.88e+08,
       2.00e+05,      nan, 1.00e+06, 3.00e+06, 1.00e+05, 7.00e+05,
       9.00e+06, 4.00e+07, 4.90e+07, 4.00e+05, 3.00e+05, 2.50e+07,
       1.60e+08, 1.50e+05, 1.80e+06, 5.00e+06, 8.50e+05, 5.30e+07,
       5.00e+05, 1.10e+06, 6.00e+06, 8.00e+05, 1.00e+07, 2.10e+07,
       7.50e+06, 2.60e+07, 7.40e+06, 1.50e+06, 6.00e+05, 8.00e+08,
       1.70e+07, 3.50e+06, 1.50e+07, 2.15e+08, 2.50e+06, 3.50e+08,
       5.50e+06, 8.30e+07, 1.10e+08, 5.00e+08, 6.50e+07, 1.50e+11,
       3.00e+08, 2.20e+06, 3.50e+07, 1.40e+08, 4.00e+06, 1.30e+07,
       9.50e+06, 8.00e+06, 1.20e+07, 1.70e+06, 1.50e+08, 1.00e+08,
       2.25e+08, 6.70e+06, 1.30e+06, 2.00e+07, 2.50e+05, 5.20e+07,
       3.80e+06, 1.75e+07, 4.20e+07, 2.30e+06, 7.00e+06, 4.50e+08,
       2.80e+07, 8.50e+06, 3.70e+07, 3.70e+08, 1.60e+07, 4.40e+07,
       7.70e+05, 1.25e+08, 5.00e+07, 4.90e+06, 1.45e+08, 2.20e+07,
       7.00e+07, 6.60e+06, 3.20e+07, 2.40e+07, 7.25e+05, 4.61e

In [3077]:
#Check for misisng values again
data21['Amount($)'].isnull().sum()

150

In [3078]:
#Calculate the median Values and use that first to fill in the missing values.
median_value = data21['Amount($)'].median()
median_value 

3600000.0

In [3079]:
# Replace NaN values with mean
data21['Amount($)'].fillna(median_amount, inplace=True)

In [3080]:
data21['Amount($)'].isnull().sum()

0

The missing values and Non numeric values have been filled with the median value.

Lets now finalize the last missing value column - Stage. Lets fill this with unavailable

In [3081]:
data21['Stage'] = data21['Stage'].fillna('Unknown')
data21['Stage']

0       Pre-series A
1            Unknown
2           Series D
3           Series C
4               Seed
            ...     
1204    Pre-series A
1205        Series D
1206        Series C
1207        Series B
1208        Series A
Name: Stage, Length: 1187, dtype: object

In [3082]:
# lets check if all missing values have been handled.
data21.isnull().sum()

Company/Brand    0
HeadQuarter      0
Sector           0
Amount($)        0
Stage            0
dtype: int64

All missing values has been handled. Lets Inspect each column for anomaly or entries that need correction

IV. Inspecting Individual Columns for anomaly

In [3083]:
#Inspecting Company/Brand Column for anomaly
data21['Company/Brand'].info()

<class 'pandas.core.series.Series'>
Index: 1187 entries, 0 to 1208
Series name: Company/Brand
Non-Null Count  Dtype 
--------------  ----- 
1187 non-null   object
dtypes: object(1)
memory usage: 18.5+ KB


Company/Brand" Series contains 1187 non-null string values and has a data type of "object.This fine

In [3084]:
#Inspecting Headquarter column
data21['HeadQuarter'].unique()

array(['Chennai', 'Bangalore', 'Pune', 'New Delhi', 'Indore', 'Hyderabad',
       'Gurgaon', 'Belgaum', 'Noida', 'Mumbai', 'Andheri', 'Jaipur',
       'Ahmedabad', 'Kolkata', 'Tirunelveli', 'Thane', 'Unknown',
       'Singapore', 'Gurugram', 'Gujarat', 'Haryana', 'Kerala', 'Jodhpur',
       'nan', 'Delhi', 'Frisco', 'California', 'Dhingsara', 'New York',
       'Patna', 'San Francisco', 'San Ramon', 'Paris', 'Plano', 'Sydney',
       'San Francisco Bay Area', 'London', 'Milano', 'Palmwoods',
       'France', 'Trivandrum', 'Cochin', 'Samastipur', 'Irvine', 'Tumkur',
       'Newcastle Upon Tyne', 'Shanghai', 'Jiaxing', 'Rajastan', 'Kochi',
       'Ludhiana', 'Dehradun', 'San Franciscao', 'Tangerang', 'Berlin',
       'Seattle', 'Riyadh', 'Seoul', 'Bangkok', 'Kanpur', 'Chandigarh',
       'Warangal', 'Hyderebad', 'Odisha', 'Bihar', 'Goa', 'Tamil Nadu',
       'Uttar Pradesh', 'Bhopal', 'Bengaluru', 'Coimbatore'], dtype=object)

we see we have nan and unknown in the column. Lets have uniformity we have the one entry - unknown. lets rename nan to unknown. Also bangalore city to Bengaluru. Now lets check again the anomaly

In [3085]:
data21['HeadQuarter'] = data21['HeadQuarter'].str.replace('Bangalore','Bengaluru', case=False)
data21['HeadQuarter'] = data21['HeadQuarter'].str.replace('nan','Unknown', case=False)

In [3086]:
data21['HeadQuarter'].unique()

array(['Chennai', 'Bengaluru', 'Pune', 'New Delhi', 'Indore', 'Hyderabad',
       'Gurgaon', 'Belgaum', 'Noida', 'Mumbai', 'Andheri', 'Jaipur',
       'Ahmedabad', 'Kolkata', 'Tirunelveli', 'Thane', 'Unknown',
       'Singapore', 'Gurugram', 'Gujarat', 'Haryana', 'Kerala', 'Jodhpur',
       'Delhi', 'Frisco', 'California', 'Dhingsara', 'New York', 'Patna',
       'San Francisco', 'San Ramon', 'Paris', 'Plano', 'Sydney',
       'San Francisco Bay Area', 'London', 'Milano', 'Palmwoods',
       'France', 'Trivandrum', 'Cochin', 'Samastipur', 'Irvine', 'Tumkur',
       'Newcastle Upon Tyne', 'Shanghai', 'Jiaxing', 'Rajastan', 'Kochi',
       'Ludhiana', 'Dehradun', 'San Franciscao', 'Tangerang', 'Berlin',
       'Seattle', 'Riyadh', 'Seoul', 'Bangkok', 'Kanpur', 'Chandigarh',
       'Warangal', 'Hyderebad', 'Odisha', 'Bihar', 'Goa', 'Tamil Nadu',
       'Uttar Pradesh', 'Bhopal', 'Coimbatore'], dtype=object)

In [3087]:
data21['HeadQuarter'].info()

<class 'pandas.core.series.Series'>
Index: 1187 entries, 0 to 1208
Series name: HeadQuarter
Non-Null Count  Dtype 
--------------  ----- 
1187 non-null   object
dtypes: object(1)
memory usage: 18.5+ KB


The nan and Unknown and correct bengaluru city has been handled

In [3088]:
# 3. inpescting the amount column
data21['Amount($)'].unique()

array([1.20e+06, 1.20e+08, 3.00e+07, 5.10e+07, 2.00e+06, 1.88e+08,
       2.00e+05, 6.00e+06, 1.00e+06, 3.00e+06, 1.00e+05, 7.00e+05,
       9.00e+06, 4.00e+07, 4.90e+07, 4.00e+05, 3.00e+05, 2.50e+07,
       1.60e+08, 1.50e+05, 1.80e+06, 5.00e+06, 8.50e+05, 5.30e+07,
       5.00e+05, 1.10e+06, 8.00e+05, 1.00e+07, 2.10e+07, 7.50e+06,
       2.60e+07, 7.40e+06, 1.50e+06, 6.00e+05, 8.00e+08, 1.70e+07,
       3.50e+06, 1.50e+07, 2.15e+08, 2.50e+06, 3.50e+08, 5.50e+06,
       8.30e+07, 1.10e+08, 5.00e+08, 6.50e+07, 1.50e+11, 3.00e+08,
       2.20e+06, 3.50e+07, 1.40e+08, 4.00e+06, 1.30e+07, 9.50e+06,
       8.00e+06, 1.20e+07, 1.70e+06, 1.50e+08, 1.00e+08, 2.25e+08,
       6.70e+06, 1.30e+06, 2.00e+07, 2.50e+05, 5.20e+07, 3.80e+06,
       1.75e+07, 4.20e+07, 2.30e+06, 7.00e+06, 4.50e+08, 2.80e+07,
       8.50e+06, 3.70e+07, 3.70e+08, 1.60e+07, 4.40e+07, 7.70e+05,
       1.25e+08, 5.00e+07, 4.90e+06, 1.45e+08, 2.20e+07, 7.00e+07,
       6.60e+06, 3.20e+07, 2.40e+07, 7.25e+05, 4.61e+05, 9.60e

In [3089]:
data21['Amount($)'].info()

<class 'pandas.core.series.Series'>
Index: 1187 entries, 0 to 1208
Series name: Amount($)
Non-Null Count  Dtype  
--------------  -----  
1187 non-null   float64
dtypes: float64(1)
memory usage: 18.5 KB


The amount column contains numeric values presented as floats and have 1187 entries no missing values

In [3090]:
# 4. inspecting sector column
data21['Sector'].unique()

array(['AI startup', 'EdTech', 'B2B E-commerce', 'FinTech',
       'Home services', 'HealthTech', 'Tech Startup', 'E-commerce',
       'B2B service', 'Helathcare', 'Renewable Energy', 'Electronics',
       'IT startup', 'Food & Beverages', 'Aeorspace', 'Deep Tech',
       'Dating', 'Gaming', 'Robotics', 'Retail', 'Food', 'Oil and Energy',
       'AgriTech', 'Telecommuncation', 'Milk startup', 'AI Chatbot', 'IT',
       'Logistics', 'Hospitality', 'Fashion', 'Marketing',
       'Transportation', 'LegalTech', 'Food delivery', 'Automotive',
       'SaaS startup', 'Fantasy sports', 'Video communication',
       'Social Media', 'Skill development', 'Rental', 'Recruitment',
       'HealthCare', 'Sports', 'Computer Games', 'Consumer Goods',
       'Information Technology', 'Apparel & Fashion',
       'Logistics & Supply Chain', 'Healthtech', 'Healthcare',
       'SportsTech', 'HRTech', 'Wine & Spirits',
       'Mechanical & Industrial Engineering', 'Spiritual',
       'Financial Services', 'I

In [3091]:
data21['Sector'].info()

<class 'pandas.core.series.Series'>
Index: 1187 entries, 0 to 1208
Series name: Sector
Non-Null Count  Dtype 
--------------  ----- 
1187 non-null   object
dtypes: object(1)
memory usage: 18.5+ KB


The sector column has all 1187 entries and data type is object

In [3092]:
# 5. Inpecting the stage column
data21['Stage'].unique()

array(['Pre-series A', 'Unknown', 'Series D', 'Series C', 'Seed',
       'Series B', 'Series E', 'Pre-seed', 'Series A', 'Pre-series B',
       'Debt', '$1200000', 'Bridge', 'Seed+', 'Series F2', 'Series A+',
       'Series G', 'Series F', 'Series H', 'Series B3', 'PE', 'Series F1',
       'Pre-series A1', '$300000', 'Early seed', 'Series D1', '$6000000',
       '$1000000', 'Seies A', 'Pre-series', 'Series A2', 'Series I'],
      dtype=object)

As we can see we have some columns with numbers as objects, lets rename those to unavailable

In [3093]:
data21['Stage'] = data21['Stage'].str.replace('$1200000','Unvailable', case=False)
data21['Stage'] = data21['Stage'].str.replace('$300000','Unvailable', case=False)
data21['Stage'] = data21['Stage'].str.replace('$1000000','Unvailable', case=False)
data21['Stage'] = data21['Stage'].str.replace('$6000000','Unavailable', case=False)


In [3094]:
data21['Stage'].unique()

array(['Pre-series A', 'Unknown', 'Series D', 'Series C', 'Seed',
       'Series B', 'Series E', 'Pre-seed', 'Series A', 'Pre-series B',
       'Debt', 'Unvailable', 'Bridge', 'Seed+', 'Series F2', 'Series A+',
       'Series G', 'Series F', 'Series H', 'Series B3', 'PE', 'Series F1',
       'Pre-series A1', 'Early seed', 'Series D1', 'Unavailable',
       'Seies A', 'Pre-series', 'Series A2', 'Series I'], dtype=object)

Stage column anomalies has been fixed. Lets now add the year column and finalize 2021 data clean up

In [3095]:
# Creating a year column and filling with 2018
data21.insert(0,'Year', 2021)
data21.head()

Year   Company/Brand HeadQuarter          Sector    Amount($)         Stage
0  2021  Unbox Robotics     Chennai      AI startup   1200000.00  Pre-series A
1  2021          upGrad   Bengaluru          EdTech 120000000.00       Unknown
2  2021     Lead School        Pune          EdTech  30000000.00      Series D
3  2021         Bizongo   New Delhi  B2B E-commerce  51000000.00      Series C
4  2021        FypMoney      Indore         FinTech   2000000.00          Seed

In [3096]:
#Lets arrange the columns to the match the other datasets
# Create a list of column names in the desired order
desired_columns = ['Year', 'Company/Brand', 'Sector', 'Amount($)', 'Stage', 'HeadQuarter']

# Reindex the DataFrame with the desired column order
data21 = data21.reindex(columns=desired_columns)

data21.head()

Year   Company/Brand          Sector    Amount($)         Stage HeadQuarter
0  2021  Unbox Robotics      AI startup   1200000.00  Pre-series A     Chennai
1  2021          upGrad          EdTech 120000000.00       Unknown   Bengaluru
2  2021     Lead School          EdTech  30000000.00      Series D        Pune
3  2021         Bizongo  B2B E-commerce  51000000.00      Series C   New Delhi
4  2021        FypMoney         FinTech   2000000.00          Seed      Indore

We now all the 4 datasets cleaned now lets concat them for further analysis

## 2.3.DATA CONCATENATING
Concat the datasets together to have the one start up data set

In [3097]:
# Create a list of the datasets
datasets = [data18, data19, data20, data21]

# Concatenate the datasets vertically
final_data = pd.concat(datasets, ignore_index=True)

In [3098]:
final_data['Sector'].unique()

array(['Brand Marketing, Event Promotion, Marketing, Sponsorship, Ticketing',
       'Agriculture, Farming',
       'Credit, Financial Services, Lending, Marketplace',
       'Financial Services, FinTech',
       'E-Commerce Platforms, Retail, SaaS',
       'Cloud Infrastructure, PaaS, SaaS',
       'Internet, Leisure, Marketplace', 'Market Research',
       'Information Services, Information Technology', 'Mobile Payments',
       'B2B, Shoes', 'Internet',
       'Apps, Collaboration, Developer Platform, Enterprise Software, Messaging, Productivity Tools, Video Chat',
       'Food Delivery', 'Industrial Automation',
       'Automotive, Search Engine, Service Industry',
       'Finance, Internet, Travel',
       'Accounting, Business Information Systems, Business Travel, Finance, SaaS',
       'Artificial Intelligence, Product Search, SaaS, Service Industry, Software',
       'Internet of Things, Waste Management',
       'Air Transportation, Freight Service, Logistics, Marine Transport

## 3. DATA PREPARATION
3.1 Data engineering adding new features and refining data for modeling

In [3099]:
# Remodelling Sector column
#regex grouping convert
final_data['Sector'] = final_data['Sector'].str.lower()
final_data['Sector'] =final_data['Sector'].apply(lambda x: 'business consumer' if x == 'consumer' else x)
final_data['Sector'] =final_data['Sector'].apply(lambda x: 'e-vehicle' if x == 'ev' else x)
final_data['Sector'] =final_data['Sector'].apply(lambda x: 'tech' if x == 'it' else x)

In [3100]:
# Function for redefining the sector column.
def sector_redistribution(sector):
    if re.search(r'artificial intelligence|tech|cloud|artificial|data|internet|things|apps|android|software|'
                   r'portals|fraud detection|search engine|nanotechnology|security|saas|\bit company\b|'
                   r'computer|mobile|3d printing|funding platform|applications|file|embedded systems|'
                   r'augmented reality|drones|ar startup|]\baas\b|app|/|virtual|it startup|'
                   r'photonics|e tailor|\bai\b|ai & debt|ai company|ai chatbot|iot startup|\biot\b|'
                   r'\bsocial platform\b|\bar platform\b|\bapi platform\b|\bmlops platform\b|online storytelling|'
                   r'\bdigital platform\b|paas startup|taas startup|digital assistant', sector):
        return 'Technology'
    elif re.search('bank|fintech|finance|cryto|account|credit|venture|crowd|blockchain|fund|lending|financial|'
                 'trading|wealth|insurance|remittance|money|wealth|equity|investment|mortage|financial services|'
                 'nft|payments', sector):
        return 'Finance'
    elif re.search(r'automotive|air transport|transport|logistics|vehicle|transportation|'
                   r'aviation|vehicles|tyre|fleet|aer|mobility|aerospace|wl & rac protection|'
                   r'micro-mobility|delivery service', sector):
        return 'Transport'
    elif re.search(r'clean energy|boil &|\boil\b|energy|electricity|solar|environment', sector):
        return 'Energy'
    elif re.search(r'analytics|consulting|career|human|\berp\b|advertising|market research|advertisement|'
                   r'entrepre|recruit|\bhr\b|working|sultancy|work|job|advisory|management|legal|skill|'
                   r'crm|specific doman to individuals|information services', sector):
        return 'Business Intelligence'
    elif re.search('decor|fitness|training|wellness|design|personal care|craft|podcas|'
                   'lifestyle|matrimony|spiritual|living|cultural|home', sector):
        return 'Lifestyle'
    elif re.search('cosmetics|beauty|skincare|fashion|wear|cosmetic|textiles|eyewear|cloth|jewellery|eyeglasses', sector):
        return 'Beauty & Fashion'
    elif re.search('sports|esports|game|ball|player|manchester', sector):
        return 'Sports'
    elif re.search('edutech|education|learn|edtech', sector):
        return 'Education'
    elif re.search(r'beverages|cook|food|restaurants|catering', sector):
        return 'Food & Beverages'
    elif re.search('tourism|events|customer|hospital|wedding|travel|hosts|booking|weedding|qsr', sector):
        return 'Hospitality'
    elif re.search('2|trade|commerce|enterprise|consumer goods|commercial|business|Marketplace|'
                   'business consumer|market|marketing|retail|store|wholesale|furniture|wine & spirits|'
                   'multinational|e-|sales|tplace|packaging|warehouse|fm|product|merchandise|retail|'
                   'conglomerates|invoice discounting|supply chain|car service|service industry|'
                   'company-as-a-service|consumer service|facilities support services|facilities services', sector):
        return 'Commerce'
    elif re.search('health care|hospital|parenting|personal health|biotechnology|pharmaceutical', sector):
        return 'Health'
    elif re.search('agriculture|farming|', sector):
        return 'Agriculture'
    elif re.search('telecommunications', sector):
        return 'Telecommunication'
    elif re.search('product|productivity tools|shoes', sector):
        return 'Manufacturing'
    elif re.search('new|social news|social media', sector):
        return 'Media & Entertainment'
    else:
        return sector
 
final_data['Sector'] = final_data['Sector'].apply(sector_redistribution)


In [3101]:
final_data['Sector'].unique()

array(['Commerce', 'Agriculture', 'Finance', 'Technology',
       'Business Intelligence', 'Food & Beverages', 'Transport',
       'Education', 'Beauty & Fashion', 'Energy', 'Lifestyle',
       'Hospitality', 'Health', 'Sports'], dtype=object)

Lets Model now the Stage Column

In [3102]:
final_data['Stage'].unique()

array(['Seed', 'Series A', 'Angel', 'Series B', 'Pre-Seed',
       'Private Equity', 'Venture - Series Unknown', 'Grant',
       'Debt Financing', 'Post-IPO Debt', 'Series H', 'Series C',
       'Series E', 'Corporate Round', 'Unknown', 'Unavailable',
       'Series D', 'Secondary Market', 'Post-IPO Equity',
       'Non-equity Assistance', 'Funding Round', 'Fresh funding',
       'Pre series A', 'Series G', 'Post series A', 'Seed funding',
       'Seed fund', 'Series F', 'Series B+', 'Seed round', 'Pre-series A',
       'Pre-seed', 'Pre-series', 'Debt', 'Pre-series C', 'Pre-series B',
       'Bridge', 'Series B2', 'Pre- series A', 'Edge', 'Pre-Series B',
       'Seed A', 'Series A-1', 'Seed Funding', 'Pre-seed Round',
       'Seed Round & Series A', 'Pre Series A', 'Pre seed Round',
       'Angel Round', 'Pre series A1', 'Series E2', 'Seed Round',
       'Bridge Round', 'Pre seed round', 'Pre series B', 'Pre series C',
       'Seed Investment', 'Series D1', 'Mid series', 'Series C, D',

In [3103]:
#regex grouping convert and coming up with a function to apply to the stage column for regrouping
final_data['Stage'] = final_data['Stage'].str.lower()

In [3108]:
def group_stages(stage):
    angel_stages = ['angel','angel round']
    seed_stages = ['seed','seed+','seed round','seed a','seed funding','seed fund','seed investment','funding round', 'fresh funding']
    pre_seed_stages = ['non-equity assistance','pre-seed round','pre seed round','pre_seed','early seed','pre-seed']
    pre_series_stages = ['pre-series','bridge','bridge round','pre- series a','pre series a1','pre-series a','pre series a','pre-series b','pre series b','pre-series c','pre-series a1','pre series c']
    series_a_stages = ['seed round & series a','series a', 'series a+', 'series a-1', 'series a2','seies a','post series a']
    series_b_stages = ['series b', 'series b+', 'series b2', 'series b3','mid series']
    series_c_stages = ['series c', 'series c, d']
    later_stage_stages = ['post-ipo equity','series d', 'edge','','series d1', 'series e', 'series e2', 'series f', 'series f1', 'series f2', 'series g', 'series h', 'series i', 'later stage','corporate round','edge']
    grant_stages = ['grant']
    equity_stages = ['private equity','pe', 'secondary market']
    debt_stages = ['debt financing','post-ipo debt','debt']
    unknown_stages = ['venture - series unknown', 'unavailable','unvailable' 'unknown','unknown','unvailable']

    if any(stage in angel_stages for angel_stage in angel_stages):
        return 'Angel'
    elif any(stage in seed_stages for seed_stage in seed_stages):
        return 'Seed'
    elif any(stage in pre_seed_stages for pre_seed_stage  in pre_seed_stages):
        return 'Pre-Seed'
    elif any(stage in pre_series_stages for pre_series_stage in pre_series_stages):
        return 'Pre-Series'
    elif any(stage in series_a_stages for series_a_stage in series_a_stages):
        return 'Series A'
    elif any(stage in series_b_stages for series_b_stage in series_b_stages):
        return 'Series B'
    elif any(stage in series_c_stages for series_c_stage in series_c_stages):
        return 'Series C'
    elif any(stage in later_stage_stages for later_stage in later_stage_stages):
        return 'Later Stage'
    elif any(stage in grant_stages for grant_stage in grant_stages):
        return 'Grant'
    elif any(stage in equity_stages for equity_stage in equity_stages):
        return 'Equity'
    elif any(stage in debt_stages for debt_stage in debt_stages):
        return 'Debt Financing'
    elif any(stage in unknown_stages for unknown_stage in unknown_stages):
        return 'Unknown'
    else:
        return stage

final_data['Stage'] = final_data['Stage'].apply(group_stages)


In [3109]:
final_data['Stage'].unique()

array(['Seed', 'Series A', 'Angel', 'Series B', 'Pre-Seed', 'Equity',
       'Unknown', 'Grant', 'Debt Financing', 'Later Stage', 'Series C',
       'Pre-Series'], dtype=object)

The stage column has been categorized to:
Angel, Seed,Pre-Series, Series A, Series B, Series C, Later Stage, Equity and Debt Financing

## 3.2 EDA ANALYSIS
Checking correlationship between the variables of the datasets

In [3111]:
# Data overview
final_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2850 entries, 0 to 2849
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Year           2850 non-null   int64  
 1   Company/Brand  2850 non-null   object 
 2   Sector         2850 non-null   object 
 3   Stage          2850 non-null   object 
 4   Amount($)      2850 non-null   float64
 5   HeadQuarter    2850 non-null   object 
dtypes: float64(1), int64(1), object(4)
memory usage: 133.7+ KB


The data set has 4 categorical columns(with object datatype) and 2 numerical columns with data types - int64 and float64
data dictionary - 6 columns with 2850 rows

In [3110]:
# Describe the data
final_data.describe()

Year       Amount($)
count 2850.00         2850.00
mean  2020.02     99369125.22
std      1.09   3101192138.11
min   2018.00          720.00
25%   2020.00      1000000.00
50%   2020.00      3000000.00
75%   2021.00     12000000.00
max   2021.00 150000000000.00